// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/access_log.proto

package agentv1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessLogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserEmail       string                 `protobuf:"bytes,1,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	SourceIp        string                 `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	TargetDomain    string                 `protobuf:"bytes,3,opt,name=target_domain,json=targetDomain,proto3" json:"target_domain,omitempty"`
	TargetIp        string                 `protobuf:"bytes,4,opt,name=target_ip,json=targetIp,proto3" json:"target_ip,omitempty"`
	TargetPort      int32                  `protobuf:"varint,5,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Protocol        string                 `protobuf:"bytes,6,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Upload          int64                  `protobuf:"varint,7,opt,name=upload,proto3" json:"upload,omitempty"`
	Download        int64                  `protobuf:"varint,8,opt,name=download,proto3" json:"download,omitempty"`
	ConnectionStart *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=connection_start,json=connectionStart,proto3" json:"connection_start,omitempty"`
	ConnectionEnd   *timestamp.Timestamp   `protobuf:"bytes,10,opt,name=connection_end,json=connectionEnd,proto3" json:"connection_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccessLogEntry) Reset() {
	*x = AccessLogEntry{}
	mi := &file_agent_v1_access_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogEntry) ProtoMessage() {}

func (x *AccessLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_access_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogEntry.ProtoReflect.Descriptor instead.
func (*AccessLogEntry) Descriptor() ([]byte, []int) {
	return file_agent_v1_access_log_proto_rawDescGZIP(), []int{0}
}

func (x *AccessLogEntry) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *AccessLogEntry) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AccessLogEntry) GetTargetDomain() string {
	if x != nil {
		return x.TargetDomain
	}
	return ""
}

func (x *AccessLogEntry) GetTargetIp() string {
	if x != nil {
		return x.TargetIp
	}
	return ""
}

func (x *AccessLogEntry) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *AccessLogEntry) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AccessLogEntry) GetUpload() int64 {
	if x != nil {
		return x.Upload
	}
	return 0
}

func (x *AccessLogEntry) GetDownload() int64 {
	if x != nil {
		return x.Download
	}
	return 0
}

func (x *AccessLogEntry) GetConnectionStart() *timestamp.Timestamp {
	if x != nil {
		return x.ConnectionStart
	}
	return nil
}

func (x *AccessLogEntry) GetConnectionEnd() *timestamp.Timestamp {
	if x != nil {
		return x.ConnectionEnd
	}
	return nil
}

type AccessLogReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AccessLogEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogReport) Reset() {
	*x = AccessLogReport{}
	mi := &file_agent_v1_access_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogReport) ProtoMessage() {}

func (x *AccessLogReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_access_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogReport.ProtoReflect.Descriptor instead.
func (*AccessLogReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_access_log_proto_rawDescGZIP(), []int{1}
}

func (x *AccessLogReport) GetEntries() []*AccessLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AccessLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,3,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogResponse) Reset() {
	*x = AccessLogResponse{}
	mi := &file_agent_v1_access_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogResponse) ProtoMessage() {}

func (x *AccessLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_access_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogResponse.ProtoReflect.Descriptor instead.
func (*AccessLogResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_access_log_proto_rawDescGZIP(), []int{2}
}

func (x *AccessLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccessLogResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AccessLogResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

var File_agent_v1_access_log_proto protoreflect.FileDescriptor

const file_agent_v1_access_log_proto_rawDesc = "" +
	"\n" +
	"\x19agent/v1/access_log.proto\x12\bagent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x03\n" +
	"\x0eAccessLogEntry\x12\x1d\n" +
	"\n" +
	"user_email\x18\x01 \x01(\tR\tuserEmail\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12#\n" +
	"\rtarget_domain\x18\x03 \x01(\tR\ftargetDomain\x12\x1b\n" +
	"\ttarget_ip\x18\x04 \x01(\tR\btargetIp\x12\x1f\n" +
	"\vtarget_port\x18\x05 \x01(\x05R\n" +
	"targetPort\x12\x1a\n" +
	"\bprotocol\x18\x06 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06upload\x18\a \x01(\x03R\x06upload\x12\x1a\n" +
	"\bdownload\x18\b \x01(\x03R\bdownload\x12E\n" +
	"\x10connection_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0fconnectionStart\x12A\n" +
	"\x0econnection_end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rconnectionEnd\"E\n" +
	"\x0fAccessLogReport\x122\n" +
	"\aentries\x18\x01 \x03(\v2\x18.agent.v1.AccessLogEntryR\aentries\"n\n" +
	"\x11AccessLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaccepted_count\x18\x03 \x01(\x05R\racceptedCountB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_access_log_proto_rawDescOnce sync.Once
	file_agent_v1_access_log_proto_rawDescData []byte
)

func file_agent_v1_access_log_proto_rawDescGZIP() []byte {
	file_agent_v1_access_log_proto_rawDescOnce.Do(func() {
		file_agent_v1_access_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_access_log_proto_rawDesc), len(file_agent_v1_access_log_proto_rawDesc)))
	})
	return file_agent_v1_access_log_proto_rawDescData
}

var file_agent_v1_access_log_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_agent_v1_access_log_proto_goTypes = []any{
	(*AccessLogEntry)(nil),      // 0: agent.v1.AccessLogEntry
	(*AccessLogReport)(nil),     // 1: agent.v1.AccessLogReport
	(*AccessLogResponse)(nil),   // 2: agent.v1.AccessLogResponse
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_agent_v1_access_log_proto_depIdxs = []int32{
	3, // 0: agent.v1.AccessLogEntry.connection_start:type_name -> google.protobuf.Timestamp
	3, // 1: agent.v1.AccessLogEntry.connection_end:type_name -> google.protobuf.Timestamp
	0, // 2: agent.v1.AccessLogReport.entries:type_name -> agent.v1.AccessLogEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_agent_v1_access_log_proto_init() }
func file_agent_v1_access_log_proto_init() {
	if File_agent_v1_access_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_access_log_proto_rawDesc), len(file_agent_v1_access_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_access_log_proto_goTypes,
		DependencyIndexes: file_agent_v1_access_log_proto_depIdxs,
		MessageInfos:      file_agent_v1_access_log_proto_msgTypes,
	}.Build()
	File_agent_v1_access_log_proto = out.File
	file_agent_v1_access_log_proto_goTypes = nil
	file_agent_v1_access_log_proto_depIdxs = nil
}
