// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Heartbeat_FullMethodName              = "/agent.v1.AgentService/Heartbeat"
	AgentService_ReportStatus_FullMethodName           = "/agent.v1.AgentService/ReportStatus"
	AgentService_GetConfig_FullMethodName              = "/agent.v1.AgentService/GetConfig"
	AgentService_GetUsers_FullMethodName               = "/agent.v1.AgentService/GetUsers"
	AgentService_ReportTraffic_FullMethodName          = "/agent.v1.AgentService/ReportTraffic"
	AgentService_ReportAlive_FullMethodName            = "/agent.v1.AgentService/ReportAlive"
	AgentService_StatusStream_FullMethodName           = "/agent.v1.AgentService/StatusStream"
	AgentService_GetForwardingRules_FullMethodName     = "/agent.v1.AgentService/GetForwardingRules"
	AgentService_ReportForwardingStatus_FullMethodName = "/agent.v1.AgentService/ReportForwardingStatus"
	AgentService_GetCores_FullMethodName               = "/agent.v1.AgentService/GetCores"
	AgentService_SwitchCore_FullMethodName             = "/agent.v1.AgentService/SwitchCore"
	AgentService_ReportAccessLogs_FullMethodName       = "/agent.v1.AgentService/ReportAccessLogs"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the communication interface between Agent and Panel
// Panel acts as the gRPC server, Agent connects as client
type AgentServiceClient interface {
	// Heartbeat keeps the connection alive and syncs time
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// ReportStatus reports system metrics and network traffic
	ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusResponse, error)
	// GetConfig fetches node configuration
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	// GetUsers fetches user list for the node
	GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	// ReportTraffic reports user-level traffic data
	ReportTraffic(ctx context.Context, in *TrafficReport, opts ...grpc.CallOption) (*TrafficResponse, error)
	// ReportAlive reports active user IDs
	ReportAlive(ctx context.Context, in *AliveReport, opts ...grpc.CallOption) (*AliveResponse, error)
	// StatusStream is a bidirectional stream for real-time status updates
	// Agent sends status reports, Panel can send commands
	StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusReport, StatusCommand], error)
	// GetForwardingRules fetches forwarding rules
	GetForwardingRules(ctx context.Context, in *ForwardingRulesRequest, opts ...grpc.CallOption) (*ForwardingRulesResponse, error)
	// ReportForwardingStatus reports apply result
	ReportForwardingStatus(ctx context.Context, in *ForwardingStatusReport, opts ...grpc.CallOption) (*StatusResponse, error)
	// GetCores fetches available cores and instances
	GetCores(ctx context.Context, in *GetCoresRequest, opts ...grpc.CallOption) (*GetCoresResponse, error)
	// SwitchCore requests core switch
	SwitchCore(ctx context.Context, in *SwitchCoreRequest, opts ...grpc.CallOption) (*SwitchCoreResponse, error)
	// ReportAccessLogs reports access logs
	ReportAccessLogs(ctx context.Context, in *AccessLogReport, opts ...grpc.CallOption) (*AccessLogResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, AgentService_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportTraffic(ctx context.Context, in *TrafficReport, opts ...grpc.CallOption) (*TrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportAlive(ctx context.Context, in *AliveReport, opts ...grpc.CallOption) (*AliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliveResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusReport, StatusCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StatusStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusReport, StatusCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StatusStreamClient = grpc.BidiStreamingClient[StatusReport, StatusCommand]

func (c *agentServiceClient) GetForwardingRules(ctx context.Context, in *ForwardingRulesRequest, opts ...grpc.CallOption) (*ForwardingRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardingRulesResponse)
	err := c.cc.Invoke(ctx, AgentService_GetForwardingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportForwardingStatus(ctx context.Context, in *ForwardingStatusReport, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportForwardingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetCores(ctx context.Context, in *GetCoresRequest, opts ...grpc.CallOption) (*GetCoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoresResponse)
	err := c.cc.Invoke(ctx, AgentService_GetCores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SwitchCore(ctx context.Context, in *SwitchCoreRequest, opts ...grpc.CallOption) (*SwitchCoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwitchCoreResponse)
	err := c.cc.Invoke(ctx, AgentService_SwitchCore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportAccessLogs(ctx context.Context, in *AccessLogReport, opts ...grpc.CallOption) (*AccessLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessLogResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportAccessLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the communication interface between Agent and Panel
// Panel acts as the gRPC server, Agent connects as client
type AgentServiceServer interface {
	// Heartbeat keeps the connection alive and syncs time
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// ReportStatus reports system metrics and network traffic
	ReportStatus(context.Context, *StatusReport) (*StatusResponse, error)
	// GetConfig fetches node configuration
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	// GetUsers fetches user list for the node
	GetUsers(context.Context, *UsersRequest) (*UsersResponse, error)
	// ReportTraffic reports user-level traffic data
	ReportTraffic(context.Context, *TrafficReport) (*TrafficResponse, error)
	// ReportAlive reports active user IDs
	ReportAlive(context.Context, *AliveReport) (*AliveResponse, error)
	// StatusStream is a bidirectional stream for real-time status updates
	// Agent sends status reports, Panel can send commands
	StatusStream(grpc.BidiStreamingServer[StatusReport, StatusCommand]) error
	// GetForwardingRules fetches forwarding rules
	GetForwardingRules(context.Context, *ForwardingRulesRequest) (*ForwardingRulesResponse, error)
	// ReportForwardingStatus reports apply result
	ReportForwardingStatus(context.Context, *ForwardingStatusReport) (*StatusResponse, error)
	// GetCores fetches available cores and instances
	GetCores(context.Context, *GetCoresRequest) (*GetCoresResponse, error)
	// SwitchCore requests core switch
	SwitchCore(context.Context, *SwitchCoreRequest) (*SwitchCoreResponse, error)
	// ReportAccessLogs reports access logs
	ReportAccessLogs(context.Context, *AccessLogReport) (*AccessLogResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) ReportStatus(context.Context, *StatusReport) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedAgentServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedAgentServiceServer) GetUsers(context.Context, *UsersRequest) (*UsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedAgentServiceServer) ReportTraffic(context.Context, *TrafficReport) (*TrafficResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedAgentServiceServer) ReportAlive(context.Context, *AliveReport) (*AliveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAlive not implemented")
}
func (UnimplementedAgentServiceServer) StatusStream(grpc.BidiStreamingServer[StatusReport, StatusCommand]) error {
	return status.Error(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedAgentServiceServer) GetForwardingRules(context.Context, *ForwardingRulesRequest) (*ForwardingRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForwardingRules not implemented")
}
func (UnimplementedAgentServiceServer) ReportForwardingStatus(context.Context, *ForwardingStatusReport) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportForwardingStatus not implemented")
}
func (UnimplementedAgentServiceServer) GetCores(context.Context, *GetCoresRequest) (*GetCoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCores not implemented")
}
func (UnimplementedAgentServiceServer) SwitchCore(context.Context, *SwitchCoreRequest) (*SwitchCoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SwitchCore not implemented")
}
func (UnimplementedAgentServiceServer) ReportAccessLogs(context.Context, *AccessLogReport) (*AccessLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAccessLogs not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportStatus(ctx, req.(*StatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetUsers(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportTraffic(ctx, req.(*TrafficReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliveReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportAlive(ctx, req.(*AliveReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StatusStream(&grpc.GenericServerStream[StatusReport, StatusCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StatusStreamServer = grpc.BidiStreamingServer[StatusReport, StatusCommand]

func _AgentService_GetForwardingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetForwardingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetForwardingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetForwardingRules(ctx, req.(*ForwardingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportForwardingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardingStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportForwardingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportForwardingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportForwardingStatus(ctx, req.(*ForwardingStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetCores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetCores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetCores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetCores(ctx, req.(*GetCoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SwitchCore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwitchCoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SwitchCore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SwitchCore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SwitchCore(ctx, req.(*SwitchCoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportAccessLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessLogReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportAccessLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportAccessLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportAccessLogs(ctx, req.(*AccessLogReport))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _AgentService_ReportStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _AgentService_GetConfig_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _AgentService_GetUsers_Handler,
		},
		{
			MethodName: "ReportTraffic",
			Handler:    _AgentService_ReportTraffic_Handler,
		},
		{
			MethodName: "ReportAlive",
			Handler:    _AgentService_ReportAlive_Handler,
		},
		{
			MethodName: "GetForwardingRules",
			Handler:    _AgentService_GetForwardingRules_Handler,
		},
		{
			MethodName: "ReportForwardingStatus",
			Handler:    _AgentService_ReportForwardingStatus_Handler,
		},
		{
			MethodName: "GetCores",
			Handler:    _AgentService_GetCores_Handler,
		},
		{
			MethodName: "SwitchCore",
			Handler:    _AgentService_SwitchCore_Handler,
		},
		{
			MethodName: "ReportAccessLogs",
			Handler:    _AgentService_ReportAccessLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _AgentService_StatusStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
