// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_Heartbeat_FullMethodName              = "/agent.v1.AgentService/Heartbeat"
	AgentService_ReportStatus_FullMethodName           = "/agent.v1.AgentService/ReportStatus"
	AgentService_GetConfig_FullMethodName              = "/agent.v1.AgentService/GetConfig"
	AgentService_GetUsers_FullMethodName               = "/agent.v1.AgentService/GetUsers"
	AgentService_ReportTraffic_FullMethodName          = "/agent.v1.AgentService/ReportTraffic"
	AgentService_ReportAlive_FullMethodName            = "/agent.v1.AgentService/ReportAlive"
	AgentService_StatusStream_FullMethodName           = "/agent.v1.AgentService/StatusStream"
	AgentService_GetForwardingRules_FullMethodName     = "/agent.v1.AgentService/GetForwardingRules"
	AgentService_ReportForwardingStatus_FullMethodName = "/agent.v1.AgentService/ReportForwardingStatus"
	AgentService_GetCoreOperations_FullMethodName      = "/agent.v1.AgentService/GetCoreOperations"
	AgentService_ReportCoreOperation_FullMethodName    = "/agent.v1.AgentService/ReportCoreOperation"
	AgentService_ReportAccessLogs_FullMethodName       = "/agent.v1.AgentService/ReportAccessLogs"
	AgentService_GetApplyBatch_FullMethodName          = "/agent.v1.AgentService/GetApplyBatch"
	AgentService_ReportApplyRun_FullMethodName         = "/agent.v1.AgentService/ReportApplyRun"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the communication interface between Agent and Panel
// Panel acts as the gRPC server, Agent connects as client
type AgentServiceClient interface {
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusResponse, error)
	GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error)
	GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	ReportTraffic(ctx context.Context, in *TrafficReport, opts ...grpc.CallOption) (*TrafficResponse, error)
	ReportAlive(ctx context.Context, in *AliveReport, opts ...grpc.CallOption) (*AliveResponse, error)
	StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusReport, StatusCommand], error)
	GetForwardingRules(ctx context.Context, in *ForwardingRulesRequest, opts ...grpc.CallOption) (*ForwardingRulesResponse, error)
	ReportForwardingStatus(ctx context.Context, in *ForwardingStatusReport, opts ...grpc.CallOption) (*StatusResponse, error)
	GetCoreOperations(ctx context.Context, in *GetCoreOperationsRequest, opts ...grpc.CallOption) (*GetCoreOperationsResponse, error)
	ReportCoreOperation(ctx context.Context, in *ReportCoreOperationRequest, opts ...grpc.CallOption) (*ReportCoreOperationResponse, error)
	ReportAccessLogs(ctx context.Context, in *AccessLogReport, opts ...grpc.CallOption) (*AccessLogResponse, error)
	GetApplyBatch(ctx context.Context, in *ApplyBatchRequest, opts ...grpc.CallOption) (*ApplyBatchResponse, error)
	ReportApplyRun(ctx context.Context, in *ApplyRunReport, opts ...grpc.CallOption) (*ApplyRunResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetConfig(ctx context.Context, in *ConfigRequest, opts ...grpc.CallOption) (*ConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigResponse)
	err := c.cc.Invoke(ctx, AgentService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, AgentService_GetUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportTraffic(ctx context.Context, in *TrafficReport, opts ...grpc.CallOption) (*TrafficResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrafficResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportAlive(ctx context.Context, in *AliveReport, opts ...grpc.CallOption) (*AliveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AliveResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportAlive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) StatusStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[StatusReport, StatusCommand], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_StatusStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StatusReport, StatusCommand]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StatusStreamClient = grpc.BidiStreamingClient[StatusReport, StatusCommand]

func (c *agentServiceClient) GetForwardingRules(ctx context.Context, in *ForwardingRulesRequest, opts ...grpc.CallOption) (*ForwardingRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardingRulesResponse)
	err := c.cc.Invoke(ctx, AgentService_GetForwardingRules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportForwardingStatus(ctx context.Context, in *ForwardingStatusReport, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportForwardingStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetCoreOperations(ctx context.Context, in *GetCoreOperationsRequest, opts ...grpc.CallOption) (*GetCoreOperationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCoreOperationsResponse)
	err := c.cc.Invoke(ctx, AgentService_GetCoreOperations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportCoreOperation(ctx context.Context, in *ReportCoreOperationRequest, opts ...grpc.CallOption) (*ReportCoreOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportCoreOperationResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportCoreOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportAccessLogs(ctx context.Context, in *AccessLogReport, opts ...grpc.CallOption) (*AccessLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessLogResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportAccessLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) GetApplyBatch(ctx context.Context, in *ApplyBatchRequest, opts ...grpc.CallOption) (*ApplyBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyBatchResponse)
	err := c.cc.Invoke(ctx, AgentService_GetApplyBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) ReportApplyRun(ctx context.Context, in *ApplyRunReport, opts ...grpc.CallOption) (*ApplyRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyRunResponse)
	err := c.cc.Invoke(ctx, AgentService_ReportApplyRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the communication interface between Agent and Panel
// Panel acts as the gRPC server, Agent connects as client
type AgentServiceServer interface {
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	ReportStatus(context.Context, *StatusReport) (*StatusResponse, error)
	GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error)
	GetUsers(context.Context, *UsersRequest) (*UsersResponse, error)
	ReportTraffic(context.Context, *TrafficReport) (*TrafficResponse, error)
	ReportAlive(context.Context, *AliveReport) (*AliveResponse, error)
	StatusStream(grpc.BidiStreamingServer[StatusReport, StatusCommand]) error
	GetForwardingRules(context.Context, *ForwardingRulesRequest) (*ForwardingRulesResponse, error)
	ReportForwardingStatus(context.Context, *ForwardingStatusReport) (*StatusResponse, error)
	GetCoreOperations(context.Context, *GetCoreOperationsRequest) (*GetCoreOperationsResponse, error)
	ReportCoreOperation(context.Context, *ReportCoreOperationRequest) (*ReportCoreOperationResponse, error)
	ReportAccessLogs(context.Context, *AccessLogReport) (*AccessLogResponse, error)
	GetApplyBatch(context.Context, *ApplyBatchRequest) (*ApplyBatchResponse, error)
	ReportApplyRun(context.Context, *ApplyRunReport) (*ApplyRunResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) ReportStatus(context.Context, *StatusReport) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedAgentServiceServer) GetConfig(context.Context, *ConfigRequest) (*ConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedAgentServiceServer) GetUsers(context.Context, *UsersRequest) (*UsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedAgentServiceServer) ReportTraffic(context.Context, *TrafficReport) (*TrafficResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTraffic not implemented")
}
func (UnimplementedAgentServiceServer) ReportAlive(context.Context, *AliveReport) (*AliveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAlive not implemented")
}
func (UnimplementedAgentServiceServer) StatusStream(grpc.BidiStreamingServer[StatusReport, StatusCommand]) error {
	return status.Error(codes.Unimplemented, "method StatusStream not implemented")
}
func (UnimplementedAgentServiceServer) GetForwardingRules(context.Context, *ForwardingRulesRequest) (*ForwardingRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetForwardingRules not implemented")
}
func (UnimplementedAgentServiceServer) ReportForwardingStatus(context.Context, *ForwardingStatusReport) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportForwardingStatus not implemented")
}
func (UnimplementedAgentServiceServer) GetCoreOperations(context.Context, *GetCoreOperationsRequest) (*GetCoreOperationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoreOperations not implemented")
}
func (UnimplementedAgentServiceServer) ReportCoreOperation(context.Context, *ReportCoreOperationRequest) (*ReportCoreOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportCoreOperation not implemented")
}
func (UnimplementedAgentServiceServer) ReportAccessLogs(context.Context, *AccessLogReport) (*AccessLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportAccessLogs not implemented")
}
func (UnimplementedAgentServiceServer) GetApplyBatch(context.Context, *ApplyBatchRequest) (*ApplyBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetApplyBatch not implemented")
}
func (UnimplementedAgentServiceServer) ReportApplyRun(context.Context, *ApplyRunReport) (*ApplyRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportApplyRun not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportStatus(ctx, req.(*StatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetConfig(ctx, req.(*ConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetUsers(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrafficReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportTraffic(ctx, req.(*TrafficReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportAlive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AliveReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportAlive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportAlive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportAlive(ctx, req.(*AliveReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_StatusStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).StatusStream(&grpc.GenericServerStream[StatusReport, StatusCommand]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_StatusStreamServer = grpc.BidiStreamingServer[StatusReport, StatusCommand]

func _AgentService_GetForwardingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetForwardingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetForwardingRules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetForwardingRules(ctx, req.(*ForwardingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportForwardingStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardingStatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportForwardingStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportForwardingStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportForwardingStatus(ctx, req.(*ForwardingStatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetCoreOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCoreOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetCoreOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetCoreOperations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetCoreOperations(ctx, req.(*GetCoreOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportCoreOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportCoreOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportCoreOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportCoreOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportCoreOperation(ctx, req.(*ReportCoreOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportAccessLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessLogReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportAccessLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportAccessLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportAccessLogs(ctx, req.(*AccessLogReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_GetApplyBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).GetApplyBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_GetApplyBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).GetApplyBatch(ctx, req.(*ApplyBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_ReportApplyRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRunReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).ReportApplyRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_ReportApplyRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).ReportApplyRun(ctx, req.(*ApplyRunReport))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "ReportStatus",
			Handler:    _AgentService_ReportStatus_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _AgentService_GetConfig_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _AgentService_GetUsers_Handler,
		},
		{
			MethodName: "ReportTraffic",
			Handler:    _AgentService_ReportTraffic_Handler,
		},
		{
			MethodName: "ReportAlive",
			Handler:    _AgentService_ReportAlive_Handler,
		},
		{
			MethodName: "GetForwardingRules",
			Handler:    _AgentService_GetForwardingRules_Handler,
		},
		{
			MethodName: "ReportForwardingStatus",
			Handler:    _AgentService_ReportForwardingStatus_Handler,
		},
		{
			MethodName: "GetCoreOperations",
			Handler:    _AgentService_GetCoreOperations_Handler,
		},
		{
			MethodName: "ReportCoreOperation",
			Handler:    _AgentService_ReportCoreOperation_Handler,
		},
		{
			MethodName: "ReportAccessLogs",
			Handler:    _AgentService_ReportAccessLogs_Handler,
		},
		{
			MethodName: "GetApplyBatch",
			Handler:    _AgentService_GetApplyBatch_Handler,
		},
		{
			MethodName: "ReportApplyRun",
			Handler:    _AgentService_ReportApplyRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusStream",
			Handler:       _AgentService_StatusStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent/v1/agent.proto",
}
