// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\x1a\x15agent/v1/status.proto\x1a\x15agent/v1/config.proto\x1a\x16agent/v1/traffic.proto\x1a\x19agent/v1/forwarding.proto\x1a\x13agent/v1/core.proto\x1a\x19agent/v1/access_log.proto2\xe5\x06\n" +
	"\fAgentService\x12D\n" +
	"\tHeartbeat\x12\x1a.agent.v1.HeartbeatRequest\x1a\x1b.agent.v1.HeartbeatResponse\x12@\n" +
	"\fReportStatus\x12\x16.agent.v1.StatusReport\x1a\x18.agent.v1.StatusResponse\x12>\n" +
	"\tGetConfig\x12\x17.agent.v1.ConfigRequest\x1a\x18.agent.v1.ConfigResponse\x12;\n" +
	"\bGetUsers\x12\x16.agent.v1.UsersRequest\x1a\x17.agent.v1.UsersResponse\x12C\n" +
	"\rReportTraffic\x12\x17.agent.v1.TrafficReport\x1a\x19.agent.v1.TrafficResponse\x12=\n" +
	"\vReportAlive\x12\x15.agent.v1.AliveReport\x1a\x17.agent.v1.AliveResponse\x12C\n" +
	"\fStatusStream\x12\x16.agent.v1.StatusReport\x1a\x17.agent.v1.StatusCommand(\x010\x01\x12Y\n" +
	"\x12GetForwardingRules\x12 .agent.v1.ForwardingRulesRequest\x1a!.agent.v1.ForwardingRulesResponse\x12T\n" +
	"\x16ReportForwardingStatus\x12 .agent.v1.ForwardingStatusReport\x1a\x18.agent.v1.StatusResponse\x12A\n" +
	"\bGetCores\x12\x19.agent.v1.GetCoresRequest\x1a\x1a.agent.v1.GetCoresResponse\x12G\n" +
	"\n" +
	"SwitchCore\x12\x1b.agent.v1.SwitchCoreRequest\x1a\x1c.agent.v1.SwitchCoreResponse\x12J\n" +
	"\x10ReportAccessLogs\x12\x19.agent.v1.AccessLogReport\x1a\x1b.agent.v1.AccessLogResponseB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var file_agent_v1_agent_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),        // 0: agent.v1.HeartbeatRequest
	(*StatusReport)(nil),            // 1: agent.v1.StatusReport
	(*ConfigRequest)(nil),           // 2: agent.v1.ConfigRequest
	(*UsersRequest)(nil),            // 3: agent.v1.UsersRequest
	(*TrafficReport)(nil),           // 4: agent.v1.TrafficReport
	(*AliveReport)(nil),             // 5: agent.v1.AliveReport
	(*ForwardingRulesRequest)(nil),  // 6: agent.v1.ForwardingRulesRequest
	(*ForwardingStatusReport)(nil),  // 7: agent.v1.ForwardingStatusReport
	(*GetCoresRequest)(nil),         // 8: agent.v1.GetCoresRequest
	(*SwitchCoreRequest)(nil),       // 9: agent.v1.SwitchCoreRequest
	(*AccessLogReport)(nil),         // 10: agent.v1.AccessLogReport
	(*HeartbeatResponse)(nil),       // 11: agent.v1.HeartbeatResponse
	(*StatusResponse)(nil),          // 12: agent.v1.StatusResponse
	(*ConfigResponse)(nil),          // 13: agent.v1.ConfigResponse
	(*UsersResponse)(nil),           // 14: agent.v1.UsersResponse
	(*TrafficResponse)(nil),         // 15: agent.v1.TrafficResponse
	(*AliveResponse)(nil),           // 16: agent.v1.AliveResponse
	(*StatusCommand)(nil),           // 17: agent.v1.StatusCommand
	(*ForwardingRulesResponse)(nil), // 18: agent.v1.ForwardingRulesResponse
	(*GetCoresResponse)(nil),        // 19: agent.v1.GetCoresResponse
	(*SwitchCoreResponse)(nil),      // 20: agent.v1.SwitchCoreResponse
	(*AccessLogResponse)(nil),       // 21: agent.v1.AccessLogResponse
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	0,  // 0: agent.v1.AgentService.Heartbeat:input_type -> agent.v1.HeartbeatRequest
	1,  // 1: agent.v1.AgentService.ReportStatus:input_type -> agent.v1.StatusReport
	2,  // 2: agent.v1.AgentService.GetConfig:input_type -> agent.v1.ConfigRequest
	3,  // 3: agent.v1.AgentService.GetUsers:input_type -> agent.v1.UsersRequest
	4,  // 4: agent.v1.AgentService.ReportTraffic:input_type -> agent.v1.TrafficReport
	5,  // 5: agent.v1.AgentService.ReportAlive:input_type -> agent.v1.AliveReport
	1,  // 6: agent.v1.AgentService.StatusStream:input_type -> agent.v1.StatusReport
	6,  // 7: agent.v1.AgentService.GetForwardingRules:input_type -> agent.v1.ForwardingRulesRequest
	7,  // 8: agent.v1.AgentService.ReportForwardingStatus:input_type -> agent.v1.ForwardingStatusReport
	8,  // 9: agent.v1.AgentService.GetCores:input_type -> agent.v1.GetCoresRequest
	9,  // 10: agent.v1.AgentService.SwitchCore:input_type -> agent.v1.SwitchCoreRequest
	10, // 11: agent.v1.AgentService.ReportAccessLogs:input_type -> agent.v1.AccessLogReport
	11, // 12: agent.v1.AgentService.Heartbeat:output_type -> agent.v1.HeartbeatResponse
	12, // 13: agent.v1.AgentService.ReportStatus:output_type -> agent.v1.StatusResponse
	13, // 14: agent.v1.AgentService.GetConfig:output_type -> agent.v1.ConfigResponse
	14, // 15: agent.v1.AgentService.GetUsers:output_type -> agent.v1.UsersResponse
	15, // 16: agent.v1.AgentService.ReportTraffic:output_type -> agent.v1.TrafficResponse
	16, // 17: agent.v1.AgentService.ReportAlive:output_type -> agent.v1.AliveResponse
	17, // 18: agent.v1.AgentService.StatusStream:output_type -> agent.v1.StatusCommand
	18, // 19: agent.v1.AgentService.GetForwardingRules:output_type -> agent.v1.ForwardingRulesResponse
	12, // 20: agent.v1.AgentService.ReportForwardingStatus:output_type -> agent.v1.StatusResponse
	19, // 21: agent.v1.AgentService.GetCores:output_type -> agent.v1.GetCoresResponse
	20, // 22: agent.v1.AgentService.SwitchCore:output_type -> agent.v1.SwitchCoreResponse
	21, // 23: agent.v1.AgentService.ReportAccessLogs:output_type -> agent.v1.AccessLogResponse
	12, // [12:24] is the sub-list for method output_type
	0,  // [0:12] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_status_proto_init()
	file_agent_v1_config_proto_init()
	file_agent_v1_traffic_proto_init()
	file_agent_v1_forwarding_proto_init()
	file_agent_v1_core_proto_init()
	file_agent_v1_access_log_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
