// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/config.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigRequest is sent by Agent to get node configuration
type ConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"` // For conditional requests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	mi := &file_agent_v1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ConfigRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

// ConfigResponse contains node configuration
type ConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotModified   bool                   `protobuf:"varint,2,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"` // True if etag matched (304 equivalent)
	ConfigJson    []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`     // Node configuration as JSON
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigResponse) Reset() {
	*x = ConfigResponse{}
	mi := &file_agent_v1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigResponse) ProtoMessage() {}

func (x *ConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigResponse.ProtoReflect.Descriptor instead.
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *ConfigResponse) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *ConfigResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ConfigResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UsersRequest is sent by Agent to get user list
type UsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`                                      // For conditional requests
	SinceVersion  int64                  `protobuf:"varint,3,opt,name=since_version,json=sinceVersion,proto3" json:"since_version,omitempty"` // For incremental updates
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersRequest) Reset() {
	*x = UsersRequest{}
	mi := &file_agent_v1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersRequest) ProtoMessage() {}

func (x *UsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersRequest.ProtoReflect.Descriptor instead.
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_proto_rawDescGZIP(), []int{2}
}

func (x *UsersRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *UsersRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *UsersRequest) GetSinceVersion() int64 {
	if x != nil {
		return x.SinceVersion
	}
	return 0
}

// UsersResponse contains user list
type UsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotModified   bool                   `protobuf:"varint,2,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	Users         []*UserInfo            `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	Etag          string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	mi := &file_agent_v1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_proto_rawDescGZIP(), []int{3}
}

func (x *UsersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UsersResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *UsersResponse) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UsersResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *UsersResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UserInfo contains user details
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	SpeedLimit    int64                  `protobuf:"varint,4,opt,name=speed_limit,json=speedLimit,proto3" json:"speed_limit,omitempty"`
	DeviceLimit   int32                  `protobuf:"varint,5,opt,name=device_limit,json=deviceLimit,proto3" json:"device_limit,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_agent_v1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_proto_rawDescGZIP(), []int{4}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetSpeedLimit() int64 {
	if x != nil {
		return x.SpeedLimit
	}
	return 0
}

func (x *UserInfo) GetDeviceLimit() int32 {
	if x != nil {
		return x.DeviceLimit
	}
	return 0
}

func (x *UserInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_agent_v1_config_proto protoreflect.FileDescriptor

const file_agent_v1_config_proto_rawDesc = "" +
	"\n" +
	"\x15agent/v1/config.proto\x12\bagent.v1\"<\n" +
	"\rConfigRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\"\x9c\x01\n" +
	"\x0eConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnot_modified\x18\x02 \x01(\bR\vnotModified\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"`\n" +
	"\fUsersRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12#\n" +
	"\rsince_version\x18\x03 \x01(\x03R\fsinceVersion\"\xa4\x01\n" +
	"\rUsersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnot_modified\x18\x02 \x01(\bR\vnotModified\x12(\n" +
	"\x05users\x18\x03 \x03(\v2\x12.agent.v1.UserInfoR\x05users\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"\xab\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1f\n" +
	"\vspeed_limit\x18\x04 \x01(\x03R\n" +
	"speedLimit\x12!\n" +
	"\fdevice_limit\x18\x05 \x01(\x05R\vdeviceLimit\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabledB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_config_proto_rawDescOnce sync.Once
	file_agent_v1_config_proto_rawDescData []byte
)

func file_agent_v1_config_proto_rawDescGZIP() []byte {
	file_agent_v1_config_proto_rawDescOnce.Do(func() {
		file_agent_v1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_config_proto_rawDesc), len(file_agent_v1_config_proto_rawDesc)))
	})
	return file_agent_v1_config_proto_rawDescData
}

var file_agent_v1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_v1_config_proto_goTypes = []any{
	(*ConfigRequest)(nil),  // 0: agent.v1.ConfigRequest
	(*ConfigResponse)(nil), // 1: agent.v1.ConfigResponse
	(*UsersRequest)(nil),   // 2: agent.v1.UsersRequest
	(*UsersResponse)(nil),  // 3: agent.v1.UsersResponse
	(*UserInfo)(nil),       // 4: agent.v1.UserInfo
}
var file_agent_v1_config_proto_depIdxs = []int32{
	4, // 0: agent.v1.UsersResponse.users:type_name -> agent.v1.UserInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_v1_config_proto_init() }
func file_agent_v1_config_proto_init() {
	if File_agent_v1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_config_proto_rawDesc), len(file_agent_v1_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_config_proto_goTypes,
		DependencyIndexes: file_agent_v1_config_proto_depIdxs,
		MessageInfos:      file_agent_v1_config_proto_msgTypes,
	}.Build()
	File_agent_v1_config_proto = out.File
	file_agent_v1_config_proto_goTypes = nil
	file_agent_v1_config_proto_depIdxs = nil
}
