// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/config_center.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ApplyBatchRequest asks panel for target revision artifacts.
type ApplyBatchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CoreType        string                 `protobuf:"bytes,1,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`                       // sing-box | xray
	CurrentRevision int64                  `protobuf:"varint,2,opt,name=current_revision,json=currentRevision,proto3" json:"current_revision,omitempty"` // agent current applied revision
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyBatchRequest) Reset() {
	*x = ApplyBatchRequest{}
	mi := &file_agent_v1_config_center_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBatchRequest) ProtoMessage() {}

func (x *ApplyBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_center_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBatchRequest.ProtoReflect.Descriptor instead.
func (*ApplyBatchRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_center_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyBatchRequest) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *ApplyBatchRequest) GetCurrentRevision() int64 {
	if x != nil {
		return x.CurrentRevision
	}
	return 0
}

// ApplyArtifact is a single deployable file in apply batch.
type ApplyArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	SourceTag     string                 `protobuf:"bytes,2,opt,name=source_tag,json=sourceTag,proto3" json:"source_tag,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyArtifact) Reset() {
	*x = ApplyArtifact{}
	mi := &file_agent_v1_config_center_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyArtifact) ProtoMessage() {}

func (x *ApplyArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_center_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyArtifact.ProtoReflect.Descriptor instead.
func (*ApplyArtifact) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_center_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyArtifact) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ApplyArtifact) GetSourceTag() string {
	if x != nil {
		return x.SourceTag
	}
	return ""
}

func (x *ApplyArtifact) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ApplyArtifact) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// ApplyBatchResponse returns revisioned artifact batch to agent.
type ApplyBatchResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotModified      bool                   `protobuf:"varint,2,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	RunId            string                 `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CoreType         string                 `protobuf:"bytes,4,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	TargetRevision   int64                  `protobuf:"varint,5,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	PreviousRevision int64                  `protobuf:"varint,6,opt,name=previous_revision,json=previousRevision,proto3" json:"previous_revision,omitempty"`
	Artifacts        []*ApplyArtifact       `protobuf:"bytes,7,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyBatchResponse) Reset() {
	*x = ApplyBatchResponse{}
	mi := &file_agent_v1_config_center_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyBatchResponse) ProtoMessage() {}

func (x *ApplyBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_center_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyBatchResponse.ProtoReflect.Descriptor instead.
func (*ApplyBatchResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_center_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyBatchResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *ApplyBatchResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ApplyBatchResponse) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *ApplyBatchResponse) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *ApplyBatchResponse) GetPreviousRevision() int64 {
	if x != nil {
		return x.PreviousRevision
	}
	return 0
}

func (x *ApplyBatchResponse) GetArtifacts() []*ApplyArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ApplyBatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ApplyRunReport reports apply execution result from agent.
type ApplyRunReport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunId            string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CoreType         string                 `protobuf:"bytes,2,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	TargetRevision   int64                  `protobuf:"varint,3,opt,name=target_revision,json=targetRevision,proto3" json:"target_revision,omitempty"`
	Success          bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Status           string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // success | failed | rolled_back
	ErrorMessage     string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	RollbackRevision int64                  `protobuf:"varint,7,opt,name=rollback_revision,json=rollbackRevision,proto3" json:"rollback_revision,omitempty"`
	FinishedAt       int64                  `protobuf:"varint,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyRunReport) Reset() {
	*x = ApplyRunReport{}
	mi := &file_agent_v1_config_center_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRunReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRunReport) ProtoMessage() {}

func (x *ApplyRunReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_center_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRunReport.ProtoReflect.Descriptor instead.
func (*ApplyRunReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_center_proto_rawDescGZIP(), []int{3}
}

func (x *ApplyRunReport) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ApplyRunReport) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *ApplyRunReport) GetTargetRevision() int64 {
	if x != nil {
		return x.TargetRevision
	}
	return 0
}

func (x *ApplyRunReport) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyRunReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApplyRunReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ApplyRunReport) GetRollbackRevision() int64 {
	if x != nil {
		return x.RollbackRevision
	}
	return 0
}

func (x *ApplyRunReport) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

// ApplyRunResponse acknowledges report ingestion.
type ApplyRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRunResponse) Reset() {
	*x = ApplyRunResponse{}
	mi := &file_agent_v1_config_center_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRunResponse) ProtoMessage() {}

func (x *ApplyRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_config_center_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRunResponse.ProtoReflect.Descriptor instead.
func (*ApplyRunResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_config_center_proto_rawDescGZIP(), []int{4}
}

func (x *ApplyRunResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_v1_config_center_proto protoreflect.FileDescriptor

const file_agent_v1_config_center_proto_rawDesc = "" +
	"\n" +
	"\x1cagent/v1/config_center.proto\x12\bagent.v1\"[\n" +
	"\x11ApplyBatchRequest\x12\x1b\n" +
	"\tcore_type\x18\x01 \x01(\tR\bcoreType\x12)\n" +
	"\x10current_revision\x18\x02 \x01(\x03R\x0fcurrentRevision\"\x87\x01\n" +
	"\rApplyArtifact\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"source_tag\x18\x02 \x01(\tR\tsourceTag\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\"\xb7\x02\n" +
	"\x12ApplyBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnot_modified\x18\x02 \x01(\bR\vnotModified\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x12\x1b\n" +
	"\tcore_type\x18\x04 \x01(\tR\bcoreType\x12'\n" +
	"\x0ftarget_revision\x18\x05 \x01(\x03R\x0etargetRevision\x12+\n" +
	"\x11previous_revision\x18\x06 \x01(\x03R\x10previousRevision\x125\n" +
	"\tartifacts\x18\a \x03(\v2\x17.agent.v1.ApplyArtifactR\tartifacts\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\"\x92\x02\n" +
	"\x0eApplyRunReport\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tcore_type\x18\x02 \x01(\tR\bcoreType\x12'\n" +
	"\x0ftarget_revision\x18\x03 \x01(\x03R\x0etargetRevision\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12+\n" +
	"\x11rollback_revision\x18\a \x01(\x03R\x10rollbackRevision\x12\x1f\n" +
	"\vfinished_at\x18\b \x01(\x03R\n" +
	"finishedAt\"F\n" +
	"\x10ApplyRunResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_config_center_proto_rawDescOnce sync.Once
	file_agent_v1_config_center_proto_rawDescData []byte
)

func file_agent_v1_config_center_proto_rawDescGZIP() []byte {
	file_agent_v1_config_center_proto_rawDescOnce.Do(func() {
		file_agent_v1_config_center_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_config_center_proto_rawDesc), len(file_agent_v1_config_center_proto_rawDesc)))
	})
	return file_agent_v1_config_center_proto_rawDescData
}

var file_agent_v1_config_center_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_v1_config_center_proto_goTypes = []any{
	(*ApplyBatchRequest)(nil),  // 0: agent.v1.ApplyBatchRequest
	(*ApplyArtifact)(nil),      // 1: agent.v1.ApplyArtifact
	(*ApplyBatchResponse)(nil), // 2: agent.v1.ApplyBatchResponse
	(*ApplyRunReport)(nil),     // 3: agent.v1.ApplyRunReport
	(*ApplyRunResponse)(nil),   // 4: agent.v1.ApplyRunResponse
}
var file_agent_v1_config_center_proto_depIdxs = []int32{
	1, // 0: agent.v1.ApplyBatchResponse.artifacts:type_name -> agent.v1.ApplyArtifact
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_v1_config_center_proto_init() }
func file_agent_v1_config_center_proto_init() {
	if File_agent_v1_config_center_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_config_center_proto_rawDesc), len(file_agent_v1_config_center_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_config_center_proto_goTypes,
		DependencyIndexes: file_agent_v1_config_center_proto_depIdxs,
		MessageInfos:      file_agent_v1_config_center_proto_msgTypes,
	}.Build()
	File_agent_v1_config_center_proto = out.File
	file_agent_v1_config_center_proto_goTypes = nil
	file_agent_v1_config_center_proto_depIdxs = nil
}
