// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/core.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CoreInfo describes a core type and its availability.
type CoreInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Installed     bool                   `protobuf:"varint,3,opt,name=installed,proto3" json:"installed,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreInfo) Reset() {
	*x = CoreInfo{}
	mi := &file_agent_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInfo) ProtoMessage() {}

func (x *CoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInfo.ProtoReflect.Descriptor instead.
func (*CoreInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *CoreInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CoreInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CoreInfo) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *CoreInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// CoreInstance describes a running core instance on agent.
type CoreInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CoreType      string                 `protobuf:"bytes,2,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ListenPorts   []int32                `protobuf:"varint,4,rep,packed,name=listen_ports,json=listenPorts,proto3" json:"listen_ports,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,5,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,6,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Pid           int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     int64                  `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreInstance) Reset() {
	*x = CoreInstance{}
	mi := &file_agent_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInstance) ProtoMessage() {}

func (x *CoreInstance) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInstance.ProtoReflect.Descriptor instead.
func (*CoreInstance) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *CoreInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoreInstance) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *CoreInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CoreInstance) GetListenPorts() []int32 {
	if x != nil {
		return x.ListenPorts
	}
	return nil
}

func (x *CoreInstance) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *CoreInstance) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *CoreInstance) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CoreInstance) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CoreInstance) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Legacy synchronous RPC payloads are kept temporarily so transition-period code can compile,
// but they are no longer exposed as first-class RPCs on AgentService.
type GetCoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoresRequest) Reset() {
	*x = GetCoresRequest{}
	mi := &file_agent_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresRequest) ProtoMessage() {}

func (x *GetCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresRequest.ProtoReflect.Descriptor instead.
func (*GetCoresRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{2}
}

type GetCoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cores         []*CoreInfo            `protobuf:"bytes,1,rep,name=cores,proto3" json:"cores,omitempty"`
	Instances     []*CoreInstance        `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoresResponse) Reset() {
	*x = GetCoresResponse{}
	mi := &file_agent_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresResponse) ProtoMessage() {}

func (x *GetCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresResponse.ProtoReflect.Descriptor instead.
func (*GetCoresResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *GetCoresResponse) GetCores() []*CoreInfo {
	if x != nil {
		return x.Cores
	}
	return nil
}

func (x *GetCoresResponse) GetInstances() []*CoreInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type SwitchCoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromInstanceId string                 `protobuf:"bytes,1,opt,name=from_instance_id,json=fromInstanceId,proto3" json:"from_instance_id,omitempty"`
	ToCoreType     string                 `protobuf:"bytes,2,opt,name=to_core_type,json=toCoreType,proto3" json:"to_core_type,omitempty"`
	ConfigJson     []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	SwitchId       string                 `protobuf:"bytes,4,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	ListenPorts    []int32                `protobuf:"varint,5,rep,packed,name=listen_ports,json=listenPorts,proto3" json:"listen_ports,omitempty"`
	ZeroDowntime   bool                   `protobuf:"varint,6,opt,name=zero_downtime,json=zeroDowntime,proto3" json:"zero_downtime,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SwitchCoreRequest) Reset() {
	*x = SwitchCoreRequest{}
	mi := &file_agent_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCoreRequest) ProtoMessage() {}

func (x *SwitchCoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCoreRequest.ProtoReflect.Descriptor instead.
func (*SwitchCoreRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *SwitchCoreRequest) GetFromInstanceId() string {
	if x != nil {
		return x.FromInstanceId
	}
	return ""
}

func (x *SwitchCoreRequest) GetToCoreType() string {
	if x != nil {
		return x.ToCoreType
	}
	return ""
}

func (x *SwitchCoreRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *SwitchCoreRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *SwitchCoreRequest) GetListenPorts() []int32 {
	if x != nil {
		return x.ListenPorts
	}
	return nil
}

func (x *SwitchCoreRequest) GetZeroDowntime() bool {
	if x != nil {
		return x.ZeroDowntime
	}
	return false
}

type SwitchCoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewInstanceId string                 `protobuf:"bytes,2,opt,name=new_instance_id,json=newInstanceId,proto3" json:"new_instance_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchCoreResponse) Reset() {
	*x = SwitchCoreResponse{}
	mi := &file_agent_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCoreResponse) ProtoMessage() {}

func (x *SwitchCoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCoreResponse.ProtoReflect.Descriptor instead.
func (*SwitchCoreResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchCoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwitchCoreResponse) GetNewInstanceId() string {
	if x != nil {
		return x.NewInstanceId
	}
	return ""
}

func (x *SwitchCoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SwitchCoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InstallCoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreType      string                 `protobuf:"bytes,1,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	Flavor        string                 `protobuf:"bytes,5,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Activate      bool                   `protobuf:"varint,6,opt,name=activate,proto3" json:"activate,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallCoreRequest) Reset() {
	*x = InstallCoreRequest{}
	mi := &file_agent_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCoreRequest) ProtoMessage() {}

func (x *InstallCoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCoreRequest.ProtoReflect.Descriptor instead.
func (*InstallCoreRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *InstallCoreRequest) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *InstallCoreRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InstallCoreRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallCoreRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *InstallCoreRequest) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *InstallCoreRequest) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

func (x *InstallCoreRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type InstallCoreResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Changed         bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error           string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	CoreType        string                 `protobuf:"bytes,5,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Version         string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	PreviousVersion string                 `protobuf:"bytes,7,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	Activated       bool                   `protobuf:"varint,8,opt,name=activated,proto3" json:"activated,omitempty"`
	RolledBack      bool                   `protobuf:"varint,9,opt,name=rolled_back,json=rolledBack,proto3" json:"rolled_back,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InstallCoreResponse) Reset() {
	*x = InstallCoreResponse{}
	mi := &file_agent_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCoreResponse) ProtoMessage() {}

func (x *InstallCoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCoreResponse.ProtoReflect.Descriptor instead.
func (*InstallCoreResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *InstallCoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallCoreResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *InstallCoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallCoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InstallCoreResponse) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *InstallCoreResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallCoreResponse) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *InstallCoreResponse) GetActivated() bool {
	if x != nil {
		return x.Activated
	}
	return false
}

func (x *InstallCoreResponse) GetRolledBack() bool {
	if x != nil {
		return x.RolledBack
	}
	return false
}

type CoreSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Installed     bool                   `protobuf:"varint,3,opt,name=installed,proto3" json:"installed,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreSnapshot) Reset() {
	*x = CoreSnapshot{}
	mi := &file_agent_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreSnapshot) ProtoMessage() {}

func (x *CoreSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreSnapshot.ProtoReflect.Descriptor instead.
func (*CoreSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *CoreSnapshot) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CoreSnapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CoreSnapshot) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *CoreSnapshot) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CreateCoreInstancePayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	InstanceId       string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ConfigJson       []byte                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ConfigTemplateId int64                  `protobuf:"varint,3,opt,name=config_template_id,json=configTemplateId,proto3" json:"config_template_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateCoreInstancePayload) Reset() {
	*x = CreateCoreInstancePayload{}
	mi := &file_agent_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCoreInstancePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCoreInstancePayload) ProtoMessage() {}

func (x *CreateCoreInstancePayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCoreInstancePayload.ProtoReflect.Descriptor instead.
func (*CreateCoreInstancePayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *CreateCoreInstancePayload) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateCoreInstancePayload) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *CreateCoreInstancePayload) GetConfigTemplateId() int64 {
	if x != nil {
		return x.ConfigTemplateId
	}
	return 0
}

type SwitchCorePayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromInstanceId   string                 `protobuf:"bytes,1,opt,name=from_instance_id,json=fromInstanceId,proto3" json:"from_instance_id,omitempty"`
	ToCoreType       string                 `protobuf:"bytes,2,opt,name=to_core_type,json=toCoreType,proto3" json:"to_core_type,omitempty"`
	ConfigJson       []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	SwitchId         string                 `protobuf:"bytes,4,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	ListenPorts      []int32                `protobuf:"varint,5,rep,packed,name=listen_ports,json=listenPorts,proto3" json:"listen_ports,omitempty"`
	ZeroDowntime     bool                   `protobuf:"varint,6,opt,name=zero_downtime,json=zeroDowntime,proto3" json:"zero_downtime,omitempty"`
	ConfigTemplateId int64                  `protobuf:"varint,7,opt,name=config_template_id,json=configTemplateId,proto3" json:"config_template_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SwitchCorePayload) Reset() {
	*x = SwitchCorePayload{}
	mi := &file_agent_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCorePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCorePayload) ProtoMessage() {}

func (x *SwitchCorePayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCorePayload.ProtoReflect.Descriptor instead.
func (*SwitchCorePayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *SwitchCorePayload) GetFromInstanceId() string {
	if x != nil {
		return x.FromInstanceId
	}
	return ""
}

func (x *SwitchCorePayload) GetToCoreType() string {
	if x != nil {
		return x.ToCoreType
	}
	return ""
}

func (x *SwitchCorePayload) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *SwitchCorePayload) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *SwitchCorePayload) GetListenPorts() []int32 {
	if x != nil {
		return x.ListenPorts
	}
	return nil
}

func (x *SwitchCorePayload) GetZeroDowntime() bool {
	if x != nil {
		return x.ZeroDowntime
	}
	return false
}

func (x *SwitchCorePayload) GetConfigTemplateId() int64 {
	if x != nil {
		return x.ConfigTemplateId
	}
	return 0
}

type InstallCorePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Flavor        string                 `protobuf:"bytes,4,opt,name=flavor,proto3" json:"flavor,omitempty"`
	Activate      bool                   `protobuf:"varint,5,opt,name=activate,proto3" json:"activate,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallCorePayload) Reset() {
	*x = InstallCorePayload{}
	mi := &file_agent_v1_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCorePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCorePayload) ProtoMessage() {}

func (x *InstallCorePayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCorePayload.ProtoReflect.Descriptor instead.
func (*InstallCorePayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{11}
}

func (x *InstallCorePayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *InstallCorePayload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallCorePayload) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *InstallCorePayload) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *InstallCorePayload) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

func (x *InstallCorePayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type EnsureCorePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Flavor        string                 `protobuf:"bytes,3,opt,name=flavor,proto3" json:"flavor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureCorePayload) Reset() {
	*x = EnsureCorePayload{}
	mi := &file_agent_v1_core_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureCorePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureCorePayload) ProtoMessage() {}

func (x *EnsureCorePayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureCorePayload.ProtoReflect.Descriptor instead.
func (*EnsureCorePayload) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{12}
}

func (x *EnsureCorePayload) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EnsureCorePayload) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *EnsureCorePayload) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

type CoreOperation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AgentHostId    int64                  `protobuf:"varint,2,opt,name=agent_host_id,json=agentHostId,proto3" json:"agent_host_id,omitempty"`
	OperationType  string                 `protobuf:"bytes,3,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	CoreType       string                 `protobuf:"bytes,4,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	RequestPayload []byte                 `protobuf:"bytes,6,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	ResultPayload  []byte                 `protobuf:"bytes,7,opt,name=result_payload,json=resultPayload,proto3" json:"result_payload,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	StartedAt      int64                  `protobuf:"varint,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt     int64                  `protobuf:"varint,12,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CoreOperation) Reset() {
	*x = CoreOperation{}
	mi := &file_agent_v1_core_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreOperation) ProtoMessage() {}

func (x *CoreOperation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreOperation.ProtoReflect.Descriptor instead.
func (*CoreOperation) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{13}
}

func (x *CoreOperation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoreOperation) GetAgentHostId() int64 {
	if x != nil {
		return x.AgentHostId
	}
	return 0
}

func (x *CoreOperation) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *CoreOperation) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *CoreOperation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CoreOperation) GetRequestPayload() []byte {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *CoreOperation) GetResultPayload() []byte {
	if x != nil {
		return x.ResultPayload
	}
	return nil
}

func (x *CoreOperation) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CoreOperation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CoreOperation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *CoreOperation) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CoreOperation) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

type GetCoreOperationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []string               `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoreOperationsRequest) Reset() {
	*x = GetCoreOperationsRequest{}
	mi := &file_agent_v1_core_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoreOperationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoreOperationsRequest) ProtoMessage() {}

func (x *GetCoreOperationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoreOperationsRequest.ProtoReflect.Descriptor instead.
func (*GetCoreOperationsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{14}
}

func (x *GetCoreOperationsRequest) GetStatuses() []string {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *GetCoreOperationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCoreOperationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Operations    []*CoreOperation       `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoreOperationsResponse) Reset() {
	*x = GetCoreOperationsResponse{}
	mi := &file_agent_v1_core_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoreOperationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoreOperationsResponse) ProtoMessage() {}

func (x *GetCoreOperationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoreOperationsResponse.ProtoReflect.Descriptor instead.
func (*GetCoreOperationsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{15}
}

func (x *GetCoreOperationsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCoreOperationsResponse) GetOperations() []*CoreOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ReportCoreOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultPayload []byte                 `protobuf:"bytes,3,opt,name=result_payload,json=resultPayload,proto3" json:"result_payload,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FinishedAt    int64                  `protobuf:"varint,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCoreOperationRequest) Reset() {
	*x = ReportCoreOperationRequest{}
	mi := &file_agent_v1_core_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCoreOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCoreOperationRequest) ProtoMessage() {}

func (x *ReportCoreOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCoreOperationRequest.ProtoReflect.Descriptor instead.
func (*ReportCoreOperationRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{16}
}

func (x *ReportCoreOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ReportCoreOperationRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReportCoreOperationRequest) GetResultPayload() []byte {
	if x != nil {
		return x.ResultPayload
	}
	return nil
}

func (x *ReportCoreOperationRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportCoreOperationRequest) GetFinishedAt() int64 {
	if x != nil {
		return x.FinishedAt
	}
	return 0
}

type ReportCoreOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportCoreOperationResponse) Reset() {
	*x = ReportCoreOperationResponse{}
	mi := &file_agent_v1_core_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportCoreOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportCoreOperationResponse) ProtoMessage() {}

func (x *ReportCoreOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportCoreOperationResponse.ProtoReflect.Descriptor instead.
func (*ReportCoreOperationResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{17}
}

func (x *ReportCoreOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportCoreOperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_v1_core_proto protoreflect.FileDescriptor

const file_agent_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x13agent/v1/core.proto\x12\bagent.v1\"z\n" +
	"\bCoreInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tinstalled\x18\x03 \x01(\bR\tinstalled\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\xff\x01\n" +
	"\fCoreInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcore_type\x18\x02 \x01(\tR\bcoreType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\flisten_ports\x18\x04 \x03(\x05R\vlistenPorts\x12\x1f\n" +
	"\vconfig_path\x18\x05 \x01(\tR\n" +
	"configPath\x12\x1f\n" +
	"\vconfig_hash\x18\x06 \x01(\tR\n" +
	"configHash\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\x11\n" +
	"\x0fGetCoresRequest\"r\n" +
	"\x10GetCoresResponse\x12(\n" +
	"\x05cores\x18\x01 \x03(\v2\x12.agent.v1.CoreInfoR\x05cores\x124\n" +
	"\tinstances\x18\x02 \x03(\v2\x16.agent.v1.CoreInstanceR\tinstances\"\xe5\x01\n" +
	"\x11SwitchCoreRequest\x12(\n" +
	"\x10from_instance_id\x18\x01 \x01(\tR\x0efromInstanceId\x12 \n" +
	"\fto_core_type\x18\x02 \x01(\tR\n" +
	"toCoreType\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\x12\x1b\n" +
	"\tswitch_id\x18\x04 \x01(\tR\bswitchId\x12!\n" +
	"\flisten_ports\x18\x05 \x03(\x05R\vlistenPorts\x12#\n" +
	"\rzero_downtime\x18\x06 \x01(\bR\fzeroDowntime\"\x86\x01\n" +
	"\x12SwitchCoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fnew_instance_id\x18\x02 \x01(\tR\rnewInstanceId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xd0\x01\n" +
	"\x12InstallCoreRequest\x12\x1b\n" +
	"\tcore_type\x18\x01 \x01(\tR\bcoreType\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x16\n" +
	"\x06flavor\x18\x05 \x01(\tR\x06flavor\x12\x1a\n" +
	"\bactivate\x18\x06 \x01(\bR\bactivate\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\x9a\x02\n" +
	"\x13InstallCoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1b\n" +
	"\tcore_type\x18\x05 \x01(\tR\bcoreType\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12)\n" +
	"\x10previous_version\x18\a \x01(\tR\x0fpreviousVersion\x12\x1c\n" +
	"\tactivated\x18\b \x01(\bR\tactivated\x12\x1f\n" +
	"\vrolled_back\x18\t \x01(\bR\n" +
	"rolledBack\"~\n" +
	"\fCoreSnapshot\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tinstalled\x18\x03 \x01(\bR\tinstalled\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\x8b\x01\n" +
	"\x19CreateCoreInstancePayload\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\x12,\n" +
	"\x12config_template_id\x18\x03 \x01(\x03R\x10configTemplateId\"\x93\x02\n" +
	"\x11SwitchCorePayload\x12(\n" +
	"\x10from_instance_id\x18\x01 \x01(\tR\x0efromInstanceId\x12 \n" +
	"\fto_core_type\x18\x02 \x01(\tR\n" +
	"toCoreType\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\x12\x1b\n" +
	"\tswitch_id\x18\x04 \x01(\tR\bswitchId\x12!\n" +
	"\flisten_ports\x18\x05 \x03(\x05R\vlistenPorts\x12#\n" +
	"\rzero_downtime\x18\x06 \x01(\bR\fzeroDowntime\x12,\n" +
	"\x12config_template_id\x18\a \x01(\x03R\x10configTemplateId\"\xb3\x01\n" +
	"\x12InstallCorePayload\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x16\n" +
	"\x06flavor\x18\x04 \x01(\tR\x06flavor\x12\x1a\n" +
	"\bactivate\x18\x05 \x01(\bR\bactivate\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"_\n" +
	"\x11EnsureCorePayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x16\n" +
	"\x06flavor\x18\x03 \x01(\tR\x06flavor\"\x92\x03\n" +
	"\rCoreOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\ragent_host_id\x18\x02 \x01(\x03R\vagentHostId\x12%\n" +
	"\x0eoperation_type\x18\x03 \x01(\tR\roperationType\x12\x1b\n" +
	"\tcore_type\x18\x04 \x01(\tR\bcoreType\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12'\n" +
	"\x0frequest_payload\x18\x06 \x01(\fR\x0erequestPayload\x12%\n" +
	"\x0eresult_payload\x18\a \x01(\fR\rresultPayload\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\v \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vfinished_at\x18\f \x01(\x03R\n" +
	"finishedAt\"L\n" +
	"\x18GetCoreOperationsRequest\x12\x1a\n" +
	"\bstatuses\x18\x01 \x03(\tR\bstatuses\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"n\n" +
	"\x19GetCoreOperationsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x127\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x17.agent.v1.CoreOperationR\n" +
	"operations\"\xc4\x01\n" +
	"\x1aReportCoreOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0eresult_payload\x18\x03 \x01(\fR\rresultPayload\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vfinished_at\x18\x05 \x01(\x03R\n" +
	"finishedAt\"Q\n" +
	"\x1bReportCoreOperationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessageB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_core_proto_rawDescOnce sync.Once
	file_agent_v1_core_proto_rawDescData []byte
)

func file_agent_v1_core_proto_rawDescGZIP() []byte {
	file_agent_v1_core_proto_rawDescOnce.Do(func() {
		file_agent_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_core_proto_rawDesc), len(file_agent_v1_core_proto_rawDesc)))
	})
	return file_agent_v1_core_proto_rawDescData
}

var file_agent_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_agent_v1_core_proto_goTypes = []any{
	(*CoreInfo)(nil),                    // 0: agent.v1.CoreInfo
	(*CoreInstance)(nil),                // 1: agent.v1.CoreInstance
	(*GetCoresRequest)(nil),             // 2: agent.v1.GetCoresRequest
	(*GetCoresResponse)(nil),            // 3: agent.v1.GetCoresResponse
	(*SwitchCoreRequest)(nil),           // 4: agent.v1.SwitchCoreRequest
	(*SwitchCoreResponse)(nil),          // 5: agent.v1.SwitchCoreResponse
	(*InstallCoreRequest)(nil),          // 6: agent.v1.InstallCoreRequest
	(*InstallCoreResponse)(nil),         // 7: agent.v1.InstallCoreResponse
	(*CoreSnapshot)(nil),                // 8: agent.v1.CoreSnapshot
	(*CreateCoreInstancePayload)(nil),   // 9: agent.v1.CreateCoreInstancePayload
	(*SwitchCorePayload)(nil),           // 10: agent.v1.SwitchCorePayload
	(*InstallCorePayload)(nil),          // 11: agent.v1.InstallCorePayload
	(*EnsureCorePayload)(nil),           // 12: agent.v1.EnsureCorePayload
	(*CoreOperation)(nil),               // 13: agent.v1.CoreOperation
	(*GetCoreOperationsRequest)(nil),    // 14: agent.v1.GetCoreOperationsRequest
	(*GetCoreOperationsResponse)(nil),   // 15: agent.v1.GetCoreOperationsResponse
	(*ReportCoreOperationRequest)(nil),  // 16: agent.v1.ReportCoreOperationRequest
	(*ReportCoreOperationResponse)(nil), // 17: agent.v1.ReportCoreOperationResponse
}
var file_agent_v1_core_proto_depIdxs = []int32{
	0,  // 0: agent.v1.GetCoresResponse.cores:type_name -> agent.v1.CoreInfo
	1,  // 1: agent.v1.GetCoresResponse.instances:type_name -> agent.v1.CoreInstance
	13, // 2: agent.v1.GetCoreOperationsResponse.operations:type_name -> agent.v1.CoreOperation
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_v1_core_proto_init() }
func file_agent_v1_core_proto_init() {
	if File_agent_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_core_proto_rawDesc), len(file_agent_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_core_proto_goTypes,
		DependencyIndexes: file_agent_v1_core_proto_depIdxs,
		MessageInfos:      file_agent_v1_core_proto_msgTypes,
	}.Build()
	File_agent_v1_core_proto = out.File
	file_agent_v1_core_proto_goTypes = nil
	file_agent_v1_core_proto_depIdxs = nil
}
