// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/core.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CoreInfo describes a core type and its availability.
type CoreInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Installed     bool                   `protobuf:"varint,3,opt,name=installed,proto3" json:"installed,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreInfo) Reset() {
	*x = CoreInfo{}
	mi := &file_agent_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInfo) ProtoMessage() {}

func (x *CoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInfo.ProtoReflect.Descriptor instead.
func (*CoreInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *CoreInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CoreInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CoreInfo) GetInstalled() bool {
	if x != nil {
		return x.Installed
	}
	return false
}

func (x *CoreInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// CoreInstance describes a running core instance on agent.
type CoreInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CoreType      string                 `protobuf:"bytes,2,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ListenPorts   []int32                `protobuf:"varint,4,rep,packed,name=listen_ports,json=listenPorts,proto3" json:"listen_ports,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,5,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,6,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`
	Pid           int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	StartedAt     int64                  `protobuf:"varint,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Error         string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreInstance) Reset() {
	*x = CoreInstance{}
	mi := &file_agent_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInstance) ProtoMessage() {}

func (x *CoreInstance) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInstance.ProtoReflect.Descriptor instead.
func (*CoreInstance) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *CoreInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CoreInstance) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *CoreInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CoreInstance) GetListenPorts() []int32 {
	if x != nil {
		return x.ListenPorts
	}
	return nil
}

func (x *CoreInstance) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *CoreInstance) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

func (x *CoreInstance) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *CoreInstance) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *CoreInstance) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetCoresRequest fetches available cores and instances.
type GetCoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoresRequest) Reset() {
	*x = GetCoresRequest{}
	mi := &file_agent_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresRequest) ProtoMessage() {}

func (x *GetCoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresRequest.ProtoReflect.Descriptor instead.
func (*GetCoresRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{2}
}

// GetCoresResponse contains core info and instances.
type GetCoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cores         []*CoreInfo            `protobuf:"bytes,1,rep,name=cores,proto3" json:"cores,omitempty"`
	Instances     []*CoreInstance        `protobuf:"bytes,2,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoresResponse) Reset() {
	*x = GetCoresResponse{}
	mi := &file_agent_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoresResponse) ProtoMessage() {}

func (x *GetCoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoresResponse.ProtoReflect.Descriptor instead.
func (*GetCoresResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *GetCoresResponse) GetCores() []*CoreInfo {
	if x != nil {
		return x.Cores
	}
	return nil
}

func (x *GetCoresResponse) GetInstances() []*CoreInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

// SwitchCoreRequest requests core switch.
type SwitchCoreRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromInstanceId string                 `protobuf:"bytes,1,opt,name=from_instance_id,json=fromInstanceId,proto3" json:"from_instance_id,omitempty"`
	ToCoreType     string                 `protobuf:"bytes,2,opt,name=to_core_type,json=toCoreType,proto3" json:"to_core_type,omitempty"`
	ConfigJson     []byte                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	SwitchId       string                 `protobuf:"bytes,4,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	// listen_ports 由 Panel 显式指定，Agent 无需解析配置推导端口
	// 这避免了脆弱的配置文件解析依赖
	ListenPorts []int32 `protobuf:"varint,5,rep,packed,name=listen_ports,json=listenPorts,proto3" json:"listen_ports,omitempty"`
	// zero_downtime 指示是否启用零停机切换
	ZeroDowntime  bool `protobuf:"varint,6,opt,name=zero_downtime,json=zeroDowntime,proto3" json:"zero_downtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchCoreRequest) Reset() {
	*x = SwitchCoreRequest{}
	mi := &file_agent_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCoreRequest) ProtoMessage() {}

func (x *SwitchCoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCoreRequest.ProtoReflect.Descriptor instead.
func (*SwitchCoreRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *SwitchCoreRequest) GetFromInstanceId() string {
	if x != nil {
		return x.FromInstanceId
	}
	return ""
}

func (x *SwitchCoreRequest) GetToCoreType() string {
	if x != nil {
		return x.ToCoreType
	}
	return ""
}

func (x *SwitchCoreRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *SwitchCoreRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *SwitchCoreRequest) GetListenPorts() []int32 {
	if x != nil {
		return x.ListenPorts
	}
	return nil
}

func (x *SwitchCoreRequest) GetZeroDowntime() bool {
	if x != nil {
		return x.ZeroDowntime
	}
	return false
}

// SwitchCoreResponse reports switch result.
type SwitchCoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewInstanceId string                 `protobuf:"bytes,2,opt,name=new_instance_id,json=newInstanceId,proto3" json:"new_instance_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchCoreResponse) Reset() {
	*x = SwitchCoreResponse{}
	mi := &file_agent_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchCoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchCoreResponse) ProtoMessage() {}

func (x *SwitchCoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchCoreResponse.ProtoReflect.Descriptor instead.
func (*SwitchCoreResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchCoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwitchCoreResponse) GetNewInstanceId() string {
	if x != nil {
		return x.NewInstanceId
	}
	return ""
}

func (x *SwitchCoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SwitchCoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_v1_core_proto protoreflect.FileDescriptor

const file_agent_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x13agent/v1/core.proto\x12\bagent.v1\"z\n" +
	"\bCoreInfo\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1c\n" +
	"\tinstalled\x18\x03 \x01(\bR\tinstalled\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"\xff\x01\n" +
	"\fCoreInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tcore_type\x18\x02 \x01(\tR\bcoreType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\flisten_ports\x18\x04 \x03(\x05R\vlistenPorts\x12\x1f\n" +
	"\vconfig_path\x18\x05 \x01(\tR\n" +
	"configPath\x12\x1f\n" +
	"\vconfig_hash\x18\x06 \x01(\tR\n" +
	"configHash\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\x03R\tstartedAt\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\"\x11\n" +
	"\x0fGetCoresRequest\"r\n" +
	"\x10GetCoresResponse\x12(\n" +
	"\x05cores\x18\x01 \x03(\v2\x12.agent.v1.CoreInfoR\x05cores\x124\n" +
	"\tinstances\x18\x02 \x03(\v2\x16.agent.v1.CoreInstanceR\tinstances\"\xe5\x01\n" +
	"\x11SwitchCoreRequest\x12(\n" +
	"\x10from_instance_id\x18\x01 \x01(\tR\x0efromInstanceId\x12 \n" +
	"\fto_core_type\x18\x02 \x01(\tR\n" +
	"toCoreType\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\fR\n" +
	"configJson\x12\x1b\n" +
	"\tswitch_id\x18\x04 \x01(\tR\bswitchId\x12!\n" +
	"\flisten_ports\x18\x05 \x03(\x05R\vlistenPorts\x12#\n" +
	"\rzero_downtime\x18\x06 \x01(\bR\fzeroDowntime\"\x86\x01\n" +
	"\x12SwitchCoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fnew_instance_id\x18\x02 \x01(\tR\rnewInstanceId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_core_proto_rawDescOnce sync.Once
	file_agent_v1_core_proto_rawDescData []byte
)

func file_agent_v1_core_proto_rawDescGZIP() []byte {
	file_agent_v1_core_proto_rawDescOnce.Do(func() {
		file_agent_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_core_proto_rawDesc), len(file_agent_v1_core_proto_rawDesc)))
	})
	return file_agent_v1_core_proto_rawDescData
}

var file_agent_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_v1_core_proto_goTypes = []any{
	(*CoreInfo)(nil),           // 0: agent.v1.CoreInfo
	(*CoreInstance)(nil),       // 1: agent.v1.CoreInstance
	(*GetCoresRequest)(nil),    // 2: agent.v1.GetCoresRequest
	(*GetCoresResponse)(nil),   // 3: agent.v1.GetCoresResponse
	(*SwitchCoreRequest)(nil),  // 4: agent.v1.SwitchCoreRequest
	(*SwitchCoreResponse)(nil), // 5: agent.v1.SwitchCoreResponse
}
var file_agent_v1_core_proto_depIdxs = []int32{
	0, // 0: agent.v1.GetCoresResponse.cores:type_name -> agent.v1.CoreInfo
	1, // 1: agent.v1.GetCoresResponse.instances:type_name -> agent.v1.CoreInstance
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agent_v1_core_proto_init() }
func file_agent_v1_core_proto_init() {
	if File_agent_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_core_proto_rawDesc), len(file_agent_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_core_proto_goTypes,
		DependencyIndexes: file_agent_v1_core_proto_depIdxs,
		MessageInfos:      file_agent_v1_core_proto_msgTypes,
	}.Build()
	File_agent_v1_core_proto = out.File
	file_agent_v1_core_proto_goTypes = nil
	file_agent_v1_core_proto_depIdxs = nil
}
