// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/forwarding.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ForwardingRulesRequest is used by agent to fetch forwarding rules.
type ForwardingRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // Current local version, 0 for initial fetch.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardingRulesRequest) Reset() {
	*x = ForwardingRulesRequest{}
	mi := &file_agent_v1_forwarding_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingRulesRequest) ProtoMessage() {}

func (x *ForwardingRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_forwarding_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingRulesRequest.ProtoReflect.Descriptor instead.
func (*ForwardingRulesRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_forwarding_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardingRulesRequest) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ForwardingRulesResponse returns forwarding rules.
type ForwardingRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotModified   bool                   `protobuf:"varint,2,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	Rules         []*ForwardingRule      `protobuf:"bytes,3,rep,name=rules,proto3" json:"rules,omitempty"`
	Version       int64                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardingRulesResponse) Reset() {
	*x = ForwardingRulesResponse{}
	mi := &file_agent_v1_forwarding_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingRulesResponse) ProtoMessage() {}

func (x *ForwardingRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_forwarding_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingRulesResponse.ProtoReflect.Descriptor instead.
func (*ForwardingRulesResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_forwarding_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardingRulesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardingRulesResponse) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *ForwardingRulesResponse) GetRules() []*ForwardingRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *ForwardingRulesResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ForwardingRulesResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// ForwardingRule describes a single forwarding rule.
type ForwardingRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp/udp/both
	ListenPort    int32                  `protobuf:"varint,4,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	TargetAddress string                 `protobuf:"bytes,5,opt,name=target_address,json=targetAddress,proto3" json:"target_address,omitempty"`
	TargetPort    int32                  `protobuf:"varint,6,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	Priority      int32                  `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardingRule) Reset() {
	*x = ForwardingRule{}
	mi := &file_agent_v1_forwarding_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingRule) ProtoMessage() {}

func (x *ForwardingRule) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_forwarding_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingRule.ProtoReflect.Descriptor instead.
func (*ForwardingRule) Descriptor() ([]byte, []int) {
	return file_agent_v1_forwarding_proto_rawDescGZIP(), []int{2}
}

func (x *ForwardingRule) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForwardingRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ForwardingRule) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ForwardingRule) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *ForwardingRule) GetTargetAddress() string {
	if x != nil {
		return x.TargetAddress
	}
	return ""
}

func (x *ForwardingRule) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ForwardingRule) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ForwardingRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// ForwardingStatusReport reports apply result from agent.
type ForwardingStatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // Applied version.
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AppliedAt     int64                  `protobuf:"varint,4,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardingStatusReport) Reset() {
	*x = ForwardingStatusReport{}
	mi := &file_agent_v1_forwarding_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingStatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingStatusReport) ProtoMessage() {}

func (x *ForwardingStatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_forwarding_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingStatusReport.ProtoReflect.Descriptor instead.
func (*ForwardingStatusReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_forwarding_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardingStatusReport) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ForwardingStatusReport) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardingStatusReport) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ForwardingStatusReport) GetAppliedAt() int64 {
	if x != nil {
		return x.AppliedAt
	}
	return 0
}

var File_agent_v1_forwarding_proto protoreflect.FileDescriptor

const file_agent_v1_forwarding_proto_rawDesc = "" +
	"\n" +
	"\x19agent/v1/forwarding.proto\x12\bagent.v1\"2\n" +
	"\x16ForwardingRulesRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\"\xc5\x01\n" +
	"\x17ForwardingRulesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnot_modified\x18\x02 \x01(\bR\vnotModified\x12.\n" +
	"\x05rules\x18\x03 \x03(\v2\x18.agent.v1.ForwardingRuleR\x05rules\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x03R\aversion\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xef\x01\n" +
	"\x0eForwardingRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1f\n" +
	"\vlisten_port\x18\x04 \x01(\x05R\n" +
	"listenPort\x12%\n" +
	"\x0etarget_address\x18\x05 \x01(\tR\rtargetAddress\x12\x1f\n" +
	"\vtarget_port\x18\x06 \x01(\x05R\n" +
	"targetPort\x12\x1a\n" +
	"\bpriority\x18\a \x01(\x05R\bpriority\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\"\x90\x01\n" +
	"\x16ForwardingStatusReport\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x03R\aversion\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"applied_at\x18\x04 \x01(\x03R\tappliedAtB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_forwarding_proto_rawDescOnce sync.Once
	file_agent_v1_forwarding_proto_rawDescData []byte
)

func file_agent_v1_forwarding_proto_rawDescGZIP() []byte {
	file_agent_v1_forwarding_proto_rawDescOnce.Do(func() {
		file_agent_v1_forwarding_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_forwarding_proto_rawDesc), len(file_agent_v1_forwarding_proto_rawDesc)))
	})
	return file_agent_v1_forwarding_proto_rawDescData
}

var file_agent_v1_forwarding_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_v1_forwarding_proto_goTypes = []any{
	(*ForwardingRulesRequest)(nil),  // 0: agent.v1.ForwardingRulesRequest
	(*ForwardingRulesResponse)(nil), // 1: agent.v1.ForwardingRulesResponse
	(*ForwardingRule)(nil),          // 2: agent.v1.ForwardingRule
	(*ForwardingStatusReport)(nil),  // 3: agent.v1.ForwardingStatusReport
}
var file_agent_v1_forwarding_proto_depIdxs = []int32{
	2, // 0: agent.v1.ForwardingRulesResponse.rules:type_name -> agent.v1.ForwardingRule
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_v1_forwarding_proto_init() }
func file_agent_v1_forwarding_proto_init() {
	if File_agent_v1_forwarding_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_forwarding_proto_rawDesc), len(file_agent_v1_forwarding_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_forwarding_proto_goTypes,
		DependencyIndexes: file_agent_v1_forwarding_proto_depIdxs,
		MessageInfos:      file_agent_v1_forwarding_proto_msgTypes,
	}.Build()
	File_agent_v1_forwarding_proto = out.File
	file_agent_v1_forwarding_proto_goTypes = nil
	file_agent_v1_forwarding_proto_depIdxs = nil
}
