// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/status.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeartbeatRequest is sent by Agent to Panel periodically
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_v1_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// HeartbeatResponse is returned by Panel
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ServerTime    int64                  `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_v1_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// StatusReport contains system and network metrics
type StatusReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	System        *SystemMetrics         `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Network       *NetworkMetrics        `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Protocols     []*ProtocolState       `protobuf:"bytes,4,rep,name=protocols,proto3" json:"protocols,omitempty"`
	ClientConfigs *ClientConfigReport    `protobuf:"bytes,5,opt,name=client_configs,json=clientConfigs,proto3" json:"client_configs,omitempty"` // Client configurations from subscribe directory
	Instances     []*CoreInstance        `protobuf:"bytes,6,rep,name=instances,proto3" json:"instances,omitempty"`                              // Core instances on agent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_agent_v1_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{2}
}

func (x *StatusReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StatusReport) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *StatusReport) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *StatusReport) GetProtocols() []*ProtocolState {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *StatusReport) GetClientConfigs() *ClientConfigReport {
	if x != nil {
		return x.ClientConfigs
	}
	return nil
}

func (x *StatusReport) GetInstances() []*CoreInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

type ProtocolState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                  // Config filename (e.g. "11_vless-reality_inbounds.json")
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                  // Core type (e.g. "sing-box", "xray")
	Running       bool                   `protobuf:"varint,3,opt,name=running,proto3" json:"running,omitempty"`                           // Service status
	ContentHash   string                 `protobuf:"bytes,4,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // Content hash for change detection
	Details       []*ProtocolDetails     `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty"`                            // Parsed protocol details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolState) Reset() {
	*x = ProtocolState{}
	mi := &file_agent_v1_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolState) ProtoMessage() {}

func (x *ProtocolState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolState.ProtoReflect.Descriptor instead.
func (*ProtocolState) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{3}
}

func (x *ProtocolState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProtocolState) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProtocolState) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *ProtocolState) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ProtocolState) GetDetails() []*ProtocolDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// ProtocolDetails contains detailed protocol configuration
type ProtocolDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"` // vless, vmess, shadowsocks, trojan, hysteria
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`           // Inbound tag
	Listen        string                 `protobuf:"bytes,3,opt,name=listen,proto3" json:"listen,omitempty"`     // Listen address
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`        // Listen port
	Transport     *TransportConfig       `protobuf:"bytes,5,opt,name=transport,proto3" json:"transport,omitempty"`
	Tls           *TLSConfig             `protobuf:"bytes,6,opt,name=tls,proto3" json:"tls,omitempty"`
	Users         []*ProtocolUserInfo    `protobuf:"bytes,7,rep,name=users,proto3" json:"users,omitempty"`
	SourceFile    string                 `protobuf:"bytes,8,opt,name=source_file,json=sourceFile,proto3" json:"source_file,omitempty"`
	CoreType      string                 `protobuf:"bytes,9,opt,name=core_type,json=coreType,proto3" json:"core_type,omitempty"`
	Multiplex     *MultiplexConfig       `protobuf:"bytes,10,opt,name=multiplex,proto3" json:"multiplex,omitempty"` // Multiplex configuration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolDetails) Reset() {
	*x = ProtocolDetails{}
	mi := &file_agent_v1_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolDetails) ProtoMessage() {}

func (x *ProtocolDetails) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolDetails.ProtoReflect.Descriptor instead.
func (*ProtocolDetails) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{4}
}

func (x *ProtocolDetails) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProtocolDetails) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ProtocolDetails) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *ProtocolDetails) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProtocolDetails) GetTransport() *TransportConfig {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *ProtocolDetails) GetTls() *TLSConfig {
	if x != nil {
		return x.Tls
	}
	return nil
}

func (x *ProtocolDetails) GetUsers() []*ProtocolUserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ProtocolDetails) GetSourceFile() string {
	if x != nil {
		return x.SourceFile
	}
	return ""
}

func (x *ProtocolDetails) GetCoreType() string {
	if x != nil {
		return x.CoreType
	}
	return ""
}

func (x *ProtocolDetails) GetMultiplex() *MultiplexConfig {
	if x != nil {
		return x.Multiplex
	}
	return nil
}

// TransportConfig describes transport layer settings
type TransportConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                  // tcp, ws, grpc, http, quic, h2
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                                  // WebSocket/HTTP path
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`                                  // HTTP Host header
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // gRPC service name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportConfig) Reset() {
	*x = TransportConfig{}
	mi := &file_agent_v1_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportConfig) ProtoMessage() {}

func (x *TransportConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportConfig.ProtoReflect.Descriptor instead.
func (*TransportConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{5}
}

func (x *TransportConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransportConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TransportConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *TransportConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

// TLSConfig describes TLS settings
type TLSConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Alpn          []string               `protobuf:"bytes,3,rep,name=alpn,proto3" json:"alpn,omitempty"`
	Reality       *RealityConfig         `protobuf:"bytes,4,opt,name=reality,proto3" json:"reality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSConfig) Reset() {
	*x = TLSConfig{}
	mi := &file_agent_v1_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSConfig) ProtoMessage() {}

func (x *TLSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSConfig.ProtoReflect.Descriptor instead.
func (*TLSConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{6}
}

func (x *TLSConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *TLSConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSConfig) GetAlpn() []string {
	if x != nil {
		return x.Alpn
	}
	return nil
}

func (x *TLSConfig) GetReality() *RealityConfig {
	if x != nil {
		return x.Reality
	}
	return nil
}

// RealityConfig describes XTLS Reality settings
type RealityConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ShortIds      []string               `protobuf:"bytes,2,rep,name=short_ids,json=shortIds,proto3" json:"short_ids,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,4,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	HandshakeAddr string                 `protobuf:"bytes,5,opt,name=handshake_addr,json=handshakeAddr,proto3" json:"handshake_addr,omitempty"`  // Handshake target server
	HandshakePort int32                  `protobuf:"varint,6,opt,name=handshake_port,json=handshakePort,proto3" json:"handshake_port,omitempty"` // Handshake target port
	PublicKey     string                 `protobuf:"bytes,7,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`              // Public key (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RealityConfig) Reset() {
	*x = RealityConfig{}
	mi := &file_agent_v1_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealityConfig) ProtoMessage() {}

func (x *RealityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealityConfig.ProtoReflect.Descriptor instead.
func (*RealityConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{7}
}

func (x *RealityConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RealityConfig) GetShortIds() []string {
	if x != nil {
		return x.ShortIds
	}
	return nil
}

func (x *RealityConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RealityConfig) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *RealityConfig) GetHandshakeAddr() string {
	if x != nil {
		return x.HandshakeAddr
	}
	return ""
}

func (x *RealityConfig) GetHandshakePort() int32 {
	if x != nil {
		return x.HandshakePort
	}
	return 0
}

func (x *RealityConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

// MultiplexConfig describes multiplex (mux) settings
type MultiplexConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Padding       bool                   `protobuf:"varint,2,opt,name=padding,proto3" json:"padding,omitempty"`
	Brutal        *BrutalConfig          `protobuf:"bytes,3,opt,name=brutal,proto3" json:"brutal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiplexConfig) Reset() {
	*x = MultiplexConfig{}
	mi := &file_agent_v1_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiplexConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiplexConfig) ProtoMessage() {}

func (x *MultiplexConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiplexConfig.ProtoReflect.Descriptor instead.
func (*MultiplexConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{8}
}

func (x *MultiplexConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *MultiplexConfig) GetPadding() bool {
	if x != nil {
		return x.Padding
	}
	return false
}

func (x *MultiplexConfig) GetBrutal() *BrutalConfig {
	if x != nil {
		return x.Brutal
	}
	return nil
}

// BrutalConfig describes BBR Brutal settings
type BrutalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	UpMbps        int32                  `protobuf:"varint,2,opt,name=up_mbps,json=upMbps,proto3" json:"up_mbps,omitempty"`
	DownMbps      int32                  `protobuf:"varint,3,opt,name=down_mbps,json=downMbps,proto3" json:"down_mbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrutalConfig) Reset() {
	*x = BrutalConfig{}
	mi := &file_agent_v1_status_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrutalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrutalConfig) ProtoMessage() {}

func (x *BrutalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrutalConfig.ProtoReflect.Descriptor instead.
func (*BrutalConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{9}
}

func (x *BrutalConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BrutalConfig) GetUpMbps() int32 {
	if x != nil {
		return x.UpMbps
	}
	return 0
}

func (x *BrutalConfig) GetDownMbps() int32 {
	if x != nil {
		return x.DownMbps
	}
	return 0
}

// ProtocolUserInfo describes a user configuration in protocol
type ProtocolUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Flow          string                 `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"` // xtls-rprx-vision, etc.
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Method        string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"` // Cipher for Shadowsocks
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolUserInfo) Reset() {
	*x = ProtocolUserInfo{}
	mi := &file_agent_v1_status_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolUserInfo) ProtoMessage() {}

func (x *ProtocolUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolUserInfo.ProtoReflect.Descriptor instead.
func (*ProtocolUserInfo) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{10}
}

func (x *ProtocolUserInfo) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProtocolUserInfo) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *ProtocolUserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ProtocolUserInfo) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

// SystemMetrics contains system resource usage
type SystemMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage        float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage     float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	MemoryTotal     float64                `protobuf:"fixed64,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed      float64                `protobuf:"fixed64,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	DiskUsage       float64                `protobuf:"fixed64,5,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	DiskTotal       float64                `protobuf:"fixed64,6,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed        float64                `protobuf:"fixed64,7,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ConnectionCount int32                  `protobuf:"varint,9,opt,name=connection_count,json=connectionCount,proto3" json:"connection_count,omitempty"`
	Load1           float64                `protobuf:"fixed64,10,opt,name=load1,proto3" json:"load1,omitempty"`
	Load5           float64                `protobuf:"fixed64,11,opt,name=load5,proto3" json:"load5,omitempty"`
	Load15          float64                `protobuf:"fixed64,12,opt,name=load15,proto3" json:"load15,omitempty"`
	ProcessCount    int32                  `protobuf:"varint,13,opt,name=process_count,json=processCount,proto3" json:"process_count,omitempty"`
	TcpCount        int32                  `protobuf:"varint,14,opt,name=tcp_count,json=tcpCount,proto3" json:"tcp_count,omitempty"`
	UdpCount        int32                  `protobuf:"varint,15,opt,name=udp_count,json=udpCount,proto3" json:"udp_count,omitempty"`
	// Core capabilities (for config generation)
	CoreVersion   string   `protobuf:"bytes,20,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"` // Core version (e.g., "1.10.0")
	Capabilities  []string `protobuf:"bytes,21,rep,name=capabilities,proto3" json:"capabilities,omitempty"`                  // Detected capabilities (e.g., ["reality", "multiplex"])
	BuildTags     []string `protobuf:"bytes,22,rep,name=build_tags,json=buildTags,proto3" json:"build_tags,omitempty"`       // Build tags (e.g., ["with_v2ray_api"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_agent_v1_status_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{11}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotal() float64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsed() float64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *SystemMetrics) GetDiskTotal() float64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsed() float64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *SystemMetrics) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *SystemMetrics) GetConnectionCount() int32 {
	if x != nil {
		return x.ConnectionCount
	}
	return 0
}

func (x *SystemMetrics) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *SystemMetrics) GetLoad5() float64 {
	if x != nil {
		return x.Load5
	}
	return 0
}

func (x *SystemMetrics) GetLoad15() float64 {
	if x != nil {
		return x.Load15
	}
	return 0
}

func (x *SystemMetrics) GetProcessCount() int32 {
	if x != nil {
		return x.ProcessCount
	}
	return 0
}

func (x *SystemMetrics) GetTcpCount() int32 {
	if x != nil {
		return x.TcpCount
	}
	return 0
}

func (x *SystemMetrics) GetUdpCount() int32 {
	if x != nil {
		return x.UdpCount
	}
	return 0
}

func (x *SystemMetrics) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *SystemMetrics) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SystemMetrics) GetBuildTags() []string {
	if x != nil {
		return x.BuildTags
	}
	return nil
}

// NetworkMetrics contains network traffic statistics
type NetworkMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadBytes   uint64                 `protobuf:"varint,1,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes uint64                 `protobuf:"varint,2,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	UploadDelta   uint64                 `protobuf:"varint,3,opt,name=upload_delta,json=uploadDelta,proto3" json:"upload_delta,omitempty"`
	DownloadDelta uint64                 `protobuf:"varint,4,opt,name=download_delta,json=downloadDelta,proto3" json:"download_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_agent_v1_status_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkMetrics) GetUploadBytes() uint64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *NetworkMetrics) GetDownloadBytes() uint64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

func (x *NetworkMetrics) GetUploadDelta() uint64 {
	if x != nil {
		return x.UploadDelta
	}
	return 0
}

func (x *NetworkMetrics) GetDownloadDelta() uint64 {
	if x != nil {
		return x.DownloadDelta
	}
	return 0
}

// StatusResponse is returned after status report
type StatusResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SyncIntervalSeconds   int32                  `protobuf:"varint,3,opt,name=sync_interval_seconds,json=syncIntervalSeconds,proto3" json:"sync_interval_seconds,omitempty"`       // Panel-controlled sync interval (seconds), 0 = use default
	ReportIntervalSeconds int32                  `protobuf:"varint,4,opt,name=report_interval_seconds,json=reportIntervalSeconds,proto3" json:"report_interval_seconds,omitempty"` // Panel-controlled report interval (seconds), 0 = use default
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_agent_v1_status_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{13}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusResponse) GetSyncIntervalSeconds() int32 {
	if x != nil {
		return x.SyncIntervalSeconds
	}
	return 0
}

func (x *StatusResponse) GetReportIntervalSeconds() int32 {
	if x != nil {
		return x.ReportIntervalSeconds
	}
	return 0
}

// StatusCommand is a command sent from Panel to Agent
type StatusCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"` // Command type: "reload", "restart", "update_config", etc.
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Optional command payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCommand) Reset() {
	*x = StatusCommand{}
	mi := &file_agent_v1_status_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCommand) ProtoMessage() {}

func (x *StatusCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCommand.ProtoReflect.Descriptor instead.
func (*StatusCommand) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{14}
}

func (x *StatusCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StatusCommand) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ClientConfigReport contains client configurations parsed from subscribe directory
type ClientConfigReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ClientConfig        `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	ContentHash   string                 `protobuf:"bytes,2,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"` // For change detection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfigReport) Reset() {
	*x = ClientConfigReport{}
	mi := &file_agent_v1_status_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfigReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfigReport) ProtoMessage() {}

func (x *ClientConfigReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfigReport.ProtoReflect.Descriptor instead.
func (*ClientConfigReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{15}
}

func (x *ClientConfigReport) GetConfigs() []*ClientConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

func (x *ClientConfigReport) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

// ClientConfig represents a single protocol's client configuration
type ClientConfig struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // Protocol name/tag
	Protocol string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"` // vless, vmess, hysteria2, tuic, ss, trojan, anytls
	Server   string                 `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`     // Server address
	Port     int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`        // Main port
	// Authentication
	Uuid     string `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Password string `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	// Transport
	Network     string `protobuf:"bytes,7,opt,name=network,proto3" json:"network,omitempty"`                            // tcp, ws, grpc, http, quic
	Path        string `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`                                  // WebSocket/HTTP path
	ServiceName string `protobuf:"bytes,9,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // gRPC service name
	// TLS
	Tls         bool   `protobuf:"varint,10,opt,name=tls,proto3" json:"tls,omitempty"`
	Sni         string `protobuf:"bytes,11,opt,name=sni,proto3" json:"sni,omitempty"`
	Alpn        string `protobuf:"bytes,12,opt,name=alpn,proto3" json:"alpn,omitempty"`
	Fingerprint string `protobuf:"bytes,13,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	Insecure    bool   `protobuf:"varint,14,opt,name=insecure,proto3" json:"insecure,omitempty"`
	// Reality
	RealityEnabled   bool   `protobuf:"varint,15,opt,name=reality_enabled,json=realityEnabled,proto3" json:"reality_enabled,omitempty"`
	RealityPublicKey string `protobuf:"bytes,16,opt,name=reality_public_key,json=realityPublicKey,proto3" json:"reality_public_key,omitempty"`
	RealityShortId   string `protobuf:"bytes,17,opt,name=reality_short_id,json=realityShortId,proto3" json:"reality_short_id,omitempty"`
	// VLESS specific
	Flow string `protobuf:"bytes,18,opt,name=flow,proto3" json:"flow,omitempty"`
	// Hysteria2 specific
	HopPorts    string `protobuf:"bytes,19,opt,name=hop_ports,json=hopPorts,proto3" json:"hop_ports,omitempty"`           // Port hopping range
	HopInterval int32  `protobuf:"varint,20,opt,name=hop_interval,json=hopInterval,proto3" json:"hop_interval,omitempty"` // Hop interval in seconds
	UpMbps      int32  `protobuf:"varint,21,opt,name=up_mbps,json=upMbps,proto3" json:"up_mbps,omitempty"`
	DownMbps    int32  `protobuf:"varint,22,opt,name=down_mbps,json=downMbps,proto3" json:"down_mbps,omitempty"`
	// TUIC specific
	CongestionControl string `protobuf:"bytes,23,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	// Shadowsocks specific
	Cipher string `protobuf:"bytes,24,opt,name=cipher,proto3" json:"cipher,omitempty"`
	// ShadowTLS specific
	ShadowtlsVersion  int32  `protobuf:"varint,25,opt,name=shadowtls_version,json=shadowtlsVersion,proto3" json:"shadowtls_version,omitempty"`
	ShadowtlsPassword string `protobuf:"bytes,26,opt,name=shadowtls_password,json=shadowtlsPassword,proto3" json:"shadowtls_password,omitempty"`
	// Multiplex
	MuxEnabled bool `protobuf:"varint,27,opt,name=mux_enabled,json=muxEnabled,proto3" json:"mux_enabled,omitempty"`
	MuxPadding bool `protobuf:"varint,28,opt,name=mux_padding,json=muxPadding,proto3" json:"mux_padding,omitempty"`
	// Raw configs for direct export (format -> content)
	RawConfigs    map[string]string `protobuf:"bytes,30,rep,name=raw_configs,json=rawConfigs,proto3" json:"raw_configs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_agent_v1_status_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_status_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_agent_v1_status_proto_rawDescGZIP(), []int{16}
}

func (x *ClientConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ClientConfig) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *ClientConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClientConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ClientConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ClientConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *ClientConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ClientConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ClientConfig) GetTls() bool {
	if x != nil {
		return x.Tls
	}
	return false
}

func (x *ClientConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *ClientConfig) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *ClientConfig) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *ClientConfig) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *ClientConfig) GetRealityEnabled() bool {
	if x != nil {
		return x.RealityEnabled
	}
	return false
}

func (x *ClientConfig) GetRealityPublicKey() string {
	if x != nil {
		return x.RealityPublicKey
	}
	return ""
}

func (x *ClientConfig) GetRealityShortId() string {
	if x != nil {
		return x.RealityShortId
	}
	return ""
}

func (x *ClientConfig) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *ClientConfig) GetHopPorts() string {
	if x != nil {
		return x.HopPorts
	}
	return ""
}

func (x *ClientConfig) GetHopInterval() int32 {
	if x != nil {
		return x.HopInterval
	}
	return 0
}

func (x *ClientConfig) GetUpMbps() int32 {
	if x != nil {
		return x.UpMbps
	}
	return 0
}

func (x *ClientConfig) GetDownMbps() int32 {
	if x != nil {
		return x.DownMbps
	}
	return 0
}

func (x *ClientConfig) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *ClientConfig) GetCipher() string {
	if x != nil {
		return x.Cipher
	}
	return ""
}

func (x *ClientConfig) GetShadowtlsVersion() int32 {
	if x != nil {
		return x.ShadowtlsVersion
	}
	return 0
}

func (x *ClientConfig) GetShadowtlsPassword() string {
	if x != nil {
		return x.ShadowtlsPassword
	}
	return ""
}

func (x *ClientConfig) GetMuxEnabled() bool {
	if x != nil {
		return x.MuxEnabled
	}
	return false
}

func (x *ClientConfig) GetMuxPadding() bool {
	if x != nil {
		return x.MuxPadding
	}
	return false
}

func (x *ClientConfig) GetRawConfigs() map[string]string {
	if x != nil {
		return x.RawConfigs
	}
	return nil
}

var File_agent_v1_status_proto protoreflect.FileDescriptor

const file_agent_v1_status_proto_rawDesc = "" +
	"\n" +
	"\x15agent/v1/status.proto\x12\bagent.v1\x1a\x13agent/v1/core.proto\"0\n" +
	"\x10HeartbeatRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"N\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x03R\n" +
	"serverTime\"\xc3\x02\n" +
	"\fStatusReport\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12/\n" +
	"\x06system\x18\x02 \x01(\v2\x17.agent.v1.SystemMetricsR\x06system\x122\n" +
	"\anetwork\x18\x03 \x01(\v2\x18.agent.v1.NetworkMetricsR\anetwork\x125\n" +
	"\tprotocols\x18\x04 \x03(\v2\x17.agent.v1.ProtocolStateR\tprotocols\x12C\n" +
	"\x0eclient_configs\x18\x05 \x01(\v2\x1c.agent.v1.ClientConfigReportR\rclientConfigs\x124\n" +
	"\tinstances\x18\x06 \x03(\v2\x16.agent.v1.CoreInstanceR\tinstances\"\xa9\x01\n" +
	"\rProtocolState\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\arunning\x18\x03 \x01(\bR\arunning\x12!\n" +
	"\fcontent_hash\x18\x04 \x01(\tR\vcontentHash\x123\n" +
	"\adetails\x18\x05 \x03(\v2\x19.agent.v1.ProtocolDetailsR\adetails\"\xf4\x02\n" +
	"\x0fProtocolDetails\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x16\n" +
	"\x06listen\x18\x03 \x01(\tR\x06listen\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x127\n" +
	"\ttransport\x18\x05 \x01(\v2\x19.agent.v1.TransportConfigR\ttransport\x12%\n" +
	"\x03tls\x18\x06 \x01(\v2\x13.agent.v1.TLSConfigR\x03tls\x120\n" +
	"\x05users\x18\a \x03(\v2\x1a.agent.v1.ProtocolUserInfoR\x05users\x12\x1f\n" +
	"\vsource_file\x18\b \x01(\tR\n" +
	"sourceFile\x12\x1b\n" +
	"\tcore_type\x18\t \x01(\tR\bcoreType\x127\n" +
	"\tmultiplex\x18\n" +
	" \x01(\v2\x19.agent.v1.MultiplexConfigR\tmultiplex\"p\n" +
	"\x0fTransportConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\"\x8d\x01\n" +
	"\tTLSConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x12\n" +
	"\x04alpn\x18\x03 \x03(\tR\x04alpn\x121\n" +
	"\areality\x18\x04 \x01(\v2\x17.agent.v1.RealityConfigR\areality\"\xf6\x01\n" +
	"\rRealityConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1b\n" +
	"\tshort_ids\x18\x02 \x03(\tR\bshortIds\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12 \n" +
	"\vfingerprint\x18\x04 \x01(\tR\vfingerprint\x12%\n" +
	"\x0ehandshake_addr\x18\x05 \x01(\tR\rhandshakeAddr\x12%\n" +
	"\x0ehandshake_port\x18\x06 \x01(\x05R\rhandshakePort\x12\x1d\n" +
	"\n" +
	"public_key\x18\a \x01(\tR\tpublicKey\"u\n" +
	"\x0fMultiplexConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x18\n" +
	"\apadding\x18\x02 \x01(\bR\apadding\x12.\n" +
	"\x06brutal\x18\x03 \x01(\v2\x16.agent.v1.BrutalConfigR\x06brutal\"^\n" +
	"\fBrutalConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\aup_mbps\x18\x02 \x01(\x05R\x06upMbps\x12\x1b\n" +
	"\tdown_mbps\x18\x03 \x01(\x05R\bdownMbps\"h\n" +
	"\x10ProtocolUserInfo\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04flow\x18\x02 \x01(\tR\x04flow\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\"\xc9\x04\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x01R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x01R\n" +
	"memoryUsed\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x05 \x01(\x01R\tdiskUsage\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x06 \x01(\x01R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\a \x01(\x01R\bdiskUsed\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x12)\n" +
	"\x10connection_count\x18\t \x01(\x05R\x0fconnectionCount\x12\x14\n" +
	"\x05load1\x18\n" +
	" \x01(\x01R\x05load1\x12\x14\n" +
	"\x05load5\x18\v \x01(\x01R\x05load5\x12\x16\n" +
	"\x06load15\x18\f \x01(\x01R\x06load15\x12#\n" +
	"\rprocess_count\x18\r \x01(\x05R\fprocessCount\x12\x1b\n" +
	"\ttcp_count\x18\x0e \x01(\x05R\btcpCount\x12\x1b\n" +
	"\tudp_count\x18\x0f \x01(\x05R\budpCount\x12!\n" +
	"\fcore_version\x18\x14 \x01(\tR\vcoreVersion\x12\"\n" +
	"\fcapabilities\x18\x15 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"build_tags\x18\x16 \x03(\tR\tbuildTags\"\xa4\x01\n" +
	"\x0eNetworkMetrics\x12!\n" +
	"\fupload_bytes\x18\x01 \x01(\x04R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x02 \x01(\x04R\rdownloadBytes\x12!\n" +
	"\fupload_delta\x18\x03 \x01(\x04R\vuploadDelta\x12%\n" +
	"\x0edownload_delta\x18\x04 \x01(\x04R\rdownloadDelta\"\xb0\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\x15sync_interval_seconds\x18\x03 \x01(\x05R\x13syncIntervalSeconds\x126\n" +
	"\x17report_interval_seconds\x18\x04 \x01(\x05R\x15reportIntervalSeconds\"C\n" +
	"\rStatusCommand\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"i\n" +
	"\x12ClientConfigReport\x120\n" +
	"\aconfigs\x18\x01 \x03(\v2\x16.agent.v1.ClientConfigR\aconfigs\x12!\n" +
	"\fcontent_hash\x18\x02 \x01(\tR\vcontentHash\"\xd9\a\n" +
	"\fClientConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x16\n" +
	"\x06server\x18\x03 \x01(\tR\x06server\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x12\n" +
	"\x04uuid\x18\x05 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\x12\x18\n" +
	"\anetwork\x18\a \x01(\tR\anetwork\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12!\n" +
	"\fservice_name\x18\t \x01(\tR\vserviceName\x12\x10\n" +
	"\x03tls\x18\n" +
	" \x01(\bR\x03tls\x12\x10\n" +
	"\x03sni\x18\v \x01(\tR\x03sni\x12\x12\n" +
	"\x04alpn\x18\f \x01(\tR\x04alpn\x12 \n" +
	"\vfingerprint\x18\r \x01(\tR\vfingerprint\x12\x1a\n" +
	"\binsecure\x18\x0e \x01(\bR\binsecure\x12'\n" +
	"\x0freality_enabled\x18\x0f \x01(\bR\x0erealityEnabled\x12,\n" +
	"\x12reality_public_key\x18\x10 \x01(\tR\x10realityPublicKey\x12(\n" +
	"\x10reality_short_id\x18\x11 \x01(\tR\x0erealityShortId\x12\x12\n" +
	"\x04flow\x18\x12 \x01(\tR\x04flow\x12\x1b\n" +
	"\thop_ports\x18\x13 \x01(\tR\bhopPorts\x12!\n" +
	"\fhop_interval\x18\x14 \x01(\x05R\vhopInterval\x12\x17\n" +
	"\aup_mbps\x18\x15 \x01(\x05R\x06upMbps\x12\x1b\n" +
	"\tdown_mbps\x18\x16 \x01(\x05R\bdownMbps\x12-\n" +
	"\x12congestion_control\x18\x17 \x01(\tR\x11congestionControl\x12\x16\n" +
	"\x06cipher\x18\x18 \x01(\tR\x06cipher\x12+\n" +
	"\x11shadowtls_version\x18\x19 \x01(\x05R\x10shadowtlsVersion\x12-\n" +
	"\x12shadowtls_password\x18\x1a \x01(\tR\x11shadowtlsPassword\x12\x1f\n" +
	"\vmux_enabled\x18\x1b \x01(\bR\n" +
	"muxEnabled\x12\x1f\n" +
	"\vmux_padding\x18\x1c \x01(\bR\n" +
	"muxPadding\x12G\n" +
	"\vraw_configs\x18\x1e \x03(\v2&.agent.v1.ClientConfig.RawConfigsEntryR\n" +
	"rawConfigs\x1a=\n" +
	"\x0fRawConfigsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_status_proto_rawDescOnce sync.Once
	file_agent_v1_status_proto_rawDescData []byte
)

func file_agent_v1_status_proto_rawDescGZIP() []byte {
	file_agent_v1_status_proto_rawDescOnce.Do(func() {
		file_agent_v1_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_status_proto_rawDesc), len(file_agent_v1_status_proto_rawDesc)))
	})
	return file_agent_v1_status_proto_rawDescData
}

var file_agent_v1_status_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_agent_v1_status_proto_goTypes = []any{
	(*HeartbeatRequest)(nil),   // 0: agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),  // 1: agent.v1.HeartbeatResponse
	(*StatusReport)(nil),       // 2: agent.v1.StatusReport
	(*ProtocolState)(nil),      // 3: agent.v1.ProtocolState
	(*ProtocolDetails)(nil),    // 4: agent.v1.ProtocolDetails
	(*TransportConfig)(nil),    // 5: agent.v1.TransportConfig
	(*TLSConfig)(nil),          // 6: agent.v1.TLSConfig
	(*RealityConfig)(nil),      // 7: agent.v1.RealityConfig
	(*MultiplexConfig)(nil),    // 8: agent.v1.MultiplexConfig
	(*BrutalConfig)(nil),       // 9: agent.v1.BrutalConfig
	(*ProtocolUserInfo)(nil),   // 10: agent.v1.ProtocolUserInfo
	(*SystemMetrics)(nil),      // 11: agent.v1.SystemMetrics
	(*NetworkMetrics)(nil),     // 12: agent.v1.NetworkMetrics
	(*StatusResponse)(nil),     // 13: agent.v1.StatusResponse
	(*StatusCommand)(nil),      // 14: agent.v1.StatusCommand
	(*ClientConfigReport)(nil), // 15: agent.v1.ClientConfigReport
	(*ClientConfig)(nil),       // 16: agent.v1.ClientConfig
	nil,                        // 17: agent.v1.ClientConfig.RawConfigsEntry
	(*CoreInstance)(nil),       // 18: agent.v1.CoreInstance
}
var file_agent_v1_status_proto_depIdxs = []int32{
	11, // 0: agent.v1.StatusReport.system:type_name -> agent.v1.SystemMetrics
	12, // 1: agent.v1.StatusReport.network:type_name -> agent.v1.NetworkMetrics
	3,  // 2: agent.v1.StatusReport.protocols:type_name -> agent.v1.ProtocolState
	15, // 3: agent.v1.StatusReport.client_configs:type_name -> agent.v1.ClientConfigReport
	18, // 4: agent.v1.StatusReport.instances:type_name -> agent.v1.CoreInstance
	4,  // 5: agent.v1.ProtocolState.details:type_name -> agent.v1.ProtocolDetails
	5,  // 6: agent.v1.ProtocolDetails.transport:type_name -> agent.v1.TransportConfig
	6,  // 7: agent.v1.ProtocolDetails.tls:type_name -> agent.v1.TLSConfig
	10, // 8: agent.v1.ProtocolDetails.users:type_name -> agent.v1.ProtocolUserInfo
	8,  // 9: agent.v1.ProtocolDetails.multiplex:type_name -> agent.v1.MultiplexConfig
	7,  // 10: agent.v1.TLSConfig.reality:type_name -> agent.v1.RealityConfig
	9,  // 11: agent.v1.MultiplexConfig.brutal:type_name -> agent.v1.BrutalConfig
	16, // 12: agent.v1.ClientConfigReport.configs:type_name -> agent.v1.ClientConfig
	17, // 13: agent.v1.ClientConfig.raw_configs:type_name -> agent.v1.ClientConfig.RawConfigsEntry
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_agent_v1_status_proto_init() }
func file_agent_v1_status_proto_init() {
	if File_agent_v1_status_proto != nil {
		return
	}
	file_agent_v1_core_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_status_proto_rawDesc), len(file_agent_v1_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_status_proto_goTypes,
		DependencyIndexes: file_agent_v1_status_proto_depIdxs,
		MessageInfos:      file_agent_v1_status_proto_msgTypes,
	}.Build()
	File_agent_v1_status_proto = out.File
	file_agent_v1_status_proto_goTypes = nil
	file_agent_v1_status_proto_depIdxs = nil
}
