// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: agent/v1/traffic.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TrafficReport contains user-level traffic data
type TrafficReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserTraffic   []*UserTraffic         `protobuf:"bytes,2,rep,name=user_traffic,json=userTraffic,proto3" json:"user_traffic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_agent_v1_traffic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_traffic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_traffic_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TrafficReport) GetUserTraffic() []*UserTraffic {
	if x != nil {
		return x.UserTraffic
	}
	return nil
}

// UserTraffic contains traffic for a single user
type UserTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UploadBytes   int64                  `protobuf:"varint,2,opt,name=upload_bytes,json=uploadBytes,proto3" json:"upload_bytes,omitempty"`
	DownloadBytes int64                  `protobuf:"varint,3,opt,name=download_bytes,json=downloadBytes,proto3" json:"download_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_agent_v1_traffic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_traffic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_agent_v1_traffic_proto_rawDescGZIP(), []int{1}
}

func (x *UserTraffic) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserTraffic) GetUploadBytes() int64 {
	if x != nil {
		return x.UploadBytes
	}
	return 0
}

func (x *UserTraffic) GetDownloadBytes() int64 {
	if x != nil {
		return x.DownloadBytes
	}
	return 0
}

// TrafficResponse is returned after traffic report
type TrafficResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	AcceptedCount int32                  `protobuf:"varint,2,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficResponse) Reset() {
	*x = TrafficResponse{}
	mi := &file_agent_v1_traffic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficResponse) ProtoMessage() {}

func (x *TrafficResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_traffic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficResponse.ProtoReflect.Descriptor instead.
func (*TrafficResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_traffic_proto_rawDescGZIP(), []int{2}
}

func (x *TrafficResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrafficResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *TrafficResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AliveReport contains active user IDs
type AliveReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	UserIds       []int64                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveReport) Reset() {
	*x = AliveReport{}
	mi := &file_agent_v1_traffic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveReport) ProtoMessage() {}

func (x *AliveReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_traffic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveReport.ProtoReflect.Descriptor instead.
func (*AliveReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_traffic_proto_rawDescGZIP(), []int{3}
}

func (x *AliveReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AliveReport) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

// AliveResponse is returned after alive report
type AliveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliveResponse) Reset() {
	*x = AliveResponse{}
	mi := &file_agent_v1_traffic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliveResponse) ProtoMessage() {}

func (x *AliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_traffic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliveResponse.ProtoReflect.Descriptor instead.
func (*AliveResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_traffic_proto_rawDescGZIP(), []int{4}
}

func (x *AliveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_agent_v1_traffic_proto protoreflect.FileDescriptor

const file_agent_v1_traffic_proto_rawDesc = "" +
	"\n" +
	"\x16agent/v1/traffic.proto\x12\bagent.v1\"g\n" +
	"\rTrafficReport\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x128\n" +
	"\fuser_traffic\x18\x02 \x03(\v2\x15.agent.v1.UserTrafficR\vuserTraffic\"p\n" +
	"\vUserTraffic\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fupload_bytes\x18\x02 \x01(\x03R\vuploadBytes\x12%\n" +
	"\x0edownload_bytes\x18\x03 \x01(\x03R\rdownloadBytes\"l\n" +
	"\x0fTrafficResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x0eaccepted_count\x18\x02 \x01(\x05R\racceptedCount\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\vAliveReport\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\")\n" +
	"\rAliveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB:Z8github.com/creamcroissant/xboard/pkg/pb/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_traffic_proto_rawDescOnce sync.Once
	file_agent_v1_traffic_proto_rawDescData []byte
)

func file_agent_v1_traffic_proto_rawDescGZIP() []byte {
	file_agent_v1_traffic_proto_rawDescOnce.Do(func() {
		file_agent_v1_traffic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_traffic_proto_rawDesc), len(file_agent_v1_traffic_proto_rawDesc)))
	})
	return file_agent_v1_traffic_proto_rawDescData
}

var file_agent_v1_traffic_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_v1_traffic_proto_goTypes = []any{
	(*TrafficReport)(nil),   // 0: agent.v1.TrafficReport
	(*UserTraffic)(nil),     // 1: agent.v1.UserTraffic
	(*TrafficResponse)(nil), // 2: agent.v1.TrafficResponse
	(*AliveReport)(nil),     // 3: agent.v1.AliveReport
	(*AliveResponse)(nil),   // 4: agent.v1.AliveResponse
}
var file_agent_v1_traffic_proto_depIdxs = []int32{
	1, // 0: agent.v1.TrafficReport.user_traffic:type_name -> agent.v1.UserTraffic
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_v1_traffic_proto_init() }
func file_agent_v1_traffic_proto_init() {
	if File_agent_v1_traffic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_traffic_proto_rawDesc), len(file_agent_v1_traffic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_v1_traffic_proto_goTypes,
		DependencyIndexes: file_agent_v1_traffic_proto_depIdxs,
		MessageInfos:      file_agent_v1_traffic_proto_msgTypes,
	}.Build()
	File_agent_v1_traffic_proto = out.File
	file_agent_v1_traffic_proto_goTypes = nil
	file_agent_v1_traffic_proto_depIdxs = nil
}
